"""
会话模块 - Token 优化版
提供统一的聊天会话接口，支持多种后端

Token 优化策略:
1. 压缩系统提示词 (~200 tokens, 原 ~1000+)
2. 历史摘要：超过3轮的对话自动摘要，只传摘要+最近N轮
3. 工具输出截断：超长结果截断至 max_tool_output 字符
4. 记忆注入精简：8条记忆，独立于消息列表（不侵入 self.messages）
5. 记忆提取限窗：仅从最近6轮提取，内容截断
"""

from openai import OpenAI
from abc import ABC, abstractmethod
from typing import List, Dict, Callable, Tuple, Any, Optional
import json
import re


class BaseChatSession(ABC):
    """
    聊天会话抽象基类
    定义公共接口和共享功能
    """

    def __init__(
        self,
        model: str,
        max_history: int = 10,
        system_prompt: str = "你是一个智能助手，可以调用工具函数来帮助用户解决问题。"
    ):
        """
        初始化基类

        Args:
            model: 模型名称
            max_history: 最大历史消息数
            system_prompt: 系统提示词
        """
        self.model = model
        self.max_history = max_history
        self.system_prompt = system_prompt

        # 消息列表
        self.messages: List[Dict] = []
        self.messages.append({"role": "system", "content": self.system_prompt})

        # 打断标志
        self.interrupted = False

    @abstractmethod
    def chat_stream(self, msg: str, callback: Callable[[str], None]) -> Tuple[str, bool]:
        """
        流式对话（抽象方法，子类必须实现）

        Args:
            msg: 用户消息
            callback: 流式输出回调函数

        Returns:
            Tuple[str, bool]: (助手完整回复, 是否使用了工具调用)
        """
        pass

    def add_user_message(self, msg: str):
        """添加用户消息"""
        self.messages.append({"role": "user", "content": msg})

    def add_assistant_message(self, msg: str):
        """添加助手消息"""
        self.messages.append({"role": "assistant", "content": msg})

    def add_tool_result(self, tool_call_id: str, content: str):
        """添加工具执行结果"""
        self.messages.append({
            "role": "tool",
            "tool_call_id": tool_call_id,
            "content": content
        })

    def get_recent_messages(self) -> List[Dict]:
        """获取最近的消息（排除系统消息）"""
        return [m for m in self.messages if m["role"] != "system"]

    def load_history(self, conversations: List[Dict]):
        """
        从数据库加载历史记录，含中间工具调用链。

        如果对话有 rounds_json_parsed，则从中重建完整的工具调用链
        （assistant tool_calls → tool results → assistant final answer），
        确保 LLM 后续对话能获得正确的工具调用上下文。

        Args:
            conversations: 对话记录列表，每条含 user_msg, ai_msg,
                           is_func_calling, rounds_json_parsed 等字段
        """
        self.messages = [{"role": "system", "content": self.system_prompt}]

        for conv in conversations:
            self.messages.append({"role": "user", "content": conv["user_msg"]})

            # @2026-04-19 generated by Pro/zai-org/GLM-5.1, 从rounds重建完整工具调用链
            rounds = conv.get("rounds_json_parsed")
            if rounds and conv.get("is_func_calling"):
                # 从 rounds_json 重建中间轮次 + 最终回答
                for rd in rounds:
                    self.messages.append(rd)
            else:
                # 无工具调用或无 rounds 数据，回退到简单 user→assistant
                self.messages.append({"role": "assistant", "content": conv["ai_msg"]})

    def interrupt(self):
        """打断当前生成"""
        self.interrupted = True

    def reset_interrupt(self):
        """重置打断标志"""
        self.interrupted = False

    def _trim_messages(self):
        """裁剪消息，保持最近N条"""
        if len(self.messages) <= self.max_history * 2 + 1:
            return

        # 保留系统消息和最近的对话
        system_msg = self.messages[0]
        recent = self.messages[-(self.max_history * 2):]
        self.messages = [system_msg] + recent


# ──────────────────────────────────────────────
# LLM 驱动的记忆提取 Prompt
# ──────────────────────────────────────────────
_MEMORY_EXTRACT_SYSTEM = """你是一个专业的信息归档助手。请阅读对话记录，提取有长期保存价值的信息。

【可记忆的类别】
- user_preference：用户明确表达的偏好、习惯、风格
- fact：客观事实、知识点、概念解释
- project_info：项目相关信息（名称、技术栈、目录结构等）
- decision：技术决策、方案选择、取舍理由
- experience：经验教训、踩坑记录、最佳实践
- code_pattern：代码模式、设计模式、实现套路
- tool_usage：工具使用技巧、命令组合、工作流
- environment：环境配置、路径、依赖、版本
- general：其他有价值的信息

【提取规则】
1. 只提取有长期价值的信息，忽略寒暄、临时调试、已解决的琐碎问题
2. summary 要精炼（不超过150字），自包含，去掉"用户说"这类冗余
3. importance 为 1-5，5 = 极其重要，1 = 可记可不记
4. tags 为简短关键词数组（2-5个）
5. 如果没什么值得记的，返回空数组 []

【输出格式】
严格输出 JSON 数组，不要任何额外文字、不要 markdown 代码块。
每条格式：{"category": "...", "summary": "...", "importance": N, "tags": ["..."]}
"""

_MEMORY_EXTRACT_USER_TEMPLATE = """请提取以下对话中的记忆：

【对话记录】
{chat_text}

请直接输出 JSON 数组："""

# ──────────────────────────────────────────────
# 历史摘要 Prompt（新增）
# ──────────────────────────────────────────────
_HISTORY_SUMMARIZE_SYSTEM = (
    "将对话压缩为摘要，保留关键信息（决策、结论、事实、用户需求），"
    "忽略寒暄和过程细节。200字以内。"
)

_HISTORY_SUMMARIZE_USER = (
    "{existing}新增对话内容：\n{old_text}\n\n"
    "请输出合并后的精炼摘要（200字以内）："
)

# ──────────────────────────────────────────────
# Topic 摘要 Prompt
# ──────────────────────────────────────────────
_TOPIC_SUMMARY_SYSTEM = (
    "你是一个极简摘要生成器。根据对话内容，生成不超过20字的摘要标题。"
    "要求：精准概括对话核心主题，不使用书名号，不加引号，不加多余修饰。"
    "直接输出摘要文本，不要任何额外说明。"
)

_TOPIC_SUMMARY_USER_TEMPLATE = (
    "以下是最近3轮对话的用户消息：\n\n{user_msgs}\n\n"
    "请生成不超过20字的摘要标题："
)


class OnlineToolSession(BaseChatSession):
    """
    在线工具调用会话 - Token 优化版
    支持 OpenAI 兼容 API 的 Function Calling 功能

    Token 优化策略:
    - 历史摘要：超过 keep_turns 轮的对话自动摘要，只传摘要 + 最近 N 轮
    - 紧凑消息：工具输出和助手回复超长时截断
    - 精简系统提示词（~200 tokens，原 ~1000+）
    - 记忆注入独立于消息列表，不侵入 self.messages
    - 记忆提取限窗，仅从最近 N 轮提取

    中间轮次存储策略:
    - chat_stream 期间收集所有中间 request/response 到 _rounds_collector
    - 流结束后由调用方通过 storage.update_msg_rounds() 一次性写入 conversations 表
    - rounds_json 列存储 OpenAI API 消息格式的完整工具调用链
    """

    # ── 压缩后的系统提示词（~200 tokens，原版 ~1000+） ──
    _COMPACT_SYSTEM_PROMPT = (
        "你是可自我扩展的智能Agent。"
        "拥有工具库toolkit，可通过toolkit_save(name,meta,pycode)保存新工具、"
        "toolkit_reload()重载获得新能力。"
        "内置工具：toolkit_exec(执行命令)、toolkit_load_file(读文件)、toolkit_save_file(写文件)。\n\n"
        "核心行为：主动分析任务需求，自主创建/优化/组合工具。"
        "工具须为纯Python、可执行、有明确输入输出、通用可复用。"
        "可自由设计单函数/多函数/工具套件等结构。\n\n"
        "你不断进化，能力无上限。以最有效优雅的方式完成任务并持续增强自身。"
    )

    def __init__(
        self,
        toolkit,
        api_key: str,
        api_url: str,
        model: str = "glm-5",
        max_history: int = 10,
        system_prompt: str = "",
        max_iterations: int = 50,
        enable_thinking: bool = True,
        memory=None,
        storage=None,
        # ── 便宜模型配置（用于摘要、记忆提取等低成本任务） ──
        cheap_api_key: str = "",
        cheap_api_url: str = "",
        cheap_model: str = "",
        # ── Token 优化参数 ──
        keep_turns: int = 3,            # 保留最近N轮完整对话
        max_tool_output: int = 128 * 1024,    # 工具输出最大字符数
        max_assistant_content: int = 128 * 1024,  # 助手回复最大字符数（API传参用）
        memory_inject_limit: int = 8,   # 记忆注入条数上限
        memory_extract_rounds: int = 6, # 记忆提取窗口（最近N轮）
    ):
        """
        初始化会话

        Args:
            toolkit: Toolkit 工具库实例
            api_key: API密钥
            api_url: API地址
            model: 模型名称
            max_history: 最大历史消息数
            system_prompt: 系统提示词（为空则使用压缩版）
            max_iterations: 最大工具调用迭代次数
            enable_thinking: 是否启用 thinking 功能
            memory: Memory 实例，用于长期记忆
            storage: Storage 实例，用于持久化存储
            cheap_api_key: 便宜模型 API密钥（用于摘要等低成本任务）
            cheap_api_url: 便宜模型 API地址
            cheap_model: 便宜模型名称
            keep_turns: 保留最近N轮完整对话，更早的对话自动摘要
            max_tool_output: 工具输出截断字符数
            max_assistant_content: 助手回复截断字符数（仅截断API传参，不影响返回值）
            memory_inject_limit: 记忆注入条数上限
            memory_extract_rounds: 记忆提取窗口轮数
        """
        # 使用压缩系统提示词
        sp = system_prompt or self._COMPACT_SYSTEM_PROMPT

        super().__init__(model, max_history, sp)

        self.toolkit = toolkit
        self.client = OpenAI(api_key=api_key, base_url=api_url)
        self.max_iterations = max_iterations
        self.enable_thinking = enable_thinking

        # @2026-04-19 generated by Pro/zai-org/GLM-5.1, thinking动态检测状态
        # None=未知, True=支持, False=不支持
        self._thinking_supported: Optional[bool] = None
        self.memory = memory
        self.storage = storage

        # ── 便宜模型客户端（用于摘要、记忆提取等低成本任务） ──
        self._cheap_client: Optional[OpenAI] = None
        self._cheap_model_name: str = ""
        if cheap_api_key and cheap_api_url and cheap_model:
            self._cheap_client = OpenAI(api_key=cheap_api_key, base_url=cheap_api_url)
            self._cheap_model_name = cheap_model

        # ── Token 优化状态 ──
        self._history_summary: str = ""        # 累积的历史摘要
        self._memory_text: str = ""            # 记忆注入文本（独立于消息列表）
        self._memory_injected: bool = False

        # ── Token 统计（每次 chat_stream 累积） ──
        self._last_usage: Dict[str, int] = {
            "total_tokens": 0,
            "prompt_tokens": 0,
            "completion_tokens": 0,
        }

        # ── Token 优化参数 ──
        self.keep_turns = keep_turns
        self.max_tool_output = max_tool_output
        self.max_assistant_content = max_assistant_content
        self.memory_inject_limit = memory_inject_limit
        self.memory_extract_rounds = memory_extract_rounds

        # 记忆提取阈值：至少 N 条消息才触发提取
        self.memory_extract_threshold = 4

        # @2026-04-19 generated by Pro/zai-org/GLM-5.1, 中间轮次收集器
        # chat_stream 期间收集所有 request/response，
        # 流结束后由调用方通过 storage.update_msg_rounds() 写入 conversations
        self._rounds_collector: List[Dict] = []

        # 工具定义
        self.tools: List[Dict] = []
        self._build_tools()

        # 日志回调
        self.tool_log: Optional[Callable[[str], None]] = None

    # ──────────────────────────────────────────────
    # 基础方法
    # ──────────────────────────────────────────────

    def _build_tools(self):
        """构建工具定义列表"""
        self.tools = []
        for name, meta in self.toolkit.meta_map.items():
            self.tools.append(meta)

    def update_tools(self):
        """重新加载并刷新工具定义"""
        self.toolkit.reload()
        self._build_tools()


    def _get_summarize_client(self) -> Tuple[Any, str]:
        """
        获取用于摘要/提取任务的客户端和模型名。
        优先使用 cheap_model（降低成本），未配置时回退到主模型。

        Returns:
            Tuple[OpenAI, str]: (client, model_name)
        """
        if self._cheap_client and self._cheap_model_name:
            return self._cheap_client, self._cheap_model_name
        return self.client, self.model

    def generate_topic_summary(self, conversations: List[Dict]) -> Optional[str]:
        """
        根据最近3轮对话通过 LLM 生成不超过20字的摘要标题。

        Args:
            conversations: 最近的对话列表（按时间正序）

        Returns:
            不超过20字的摘要字符串；若生成失败则返回 None
        """
        user_msgs = []
        for conv in conversations:
            um = conv.get("user_msg", "").strip()
            if um:
                if len(um) > 200:
                    um = um[:200] + "..."
                user_msgs.append(f"用户：{um}")

        if not user_msgs:
            return None

        user_content = _TOPIC_SUMMARY_USER_TEMPLATE.format(
            user_msgs="\n".join(user_msgs)
        )

        cli, mdl = self._get_summarize_client()
        try:
            response = cli.chat.completions.create(
                model=mdl,
                messages=[
                    {"role": "system", "content": _TOPIC_SUMMARY_SYSTEM},
                    {"role": "user", "content": user_content},
                ],
                temperature=0.3,
                max_tokens=50,
            )
            raw = response.choices[0].message.content.strip()
            raw = re.sub(r'^["""\']+|["""\']+$', '', raw).strip()
            if len(raw) > 20:
                raw = raw[:20]
            return raw if raw else None
        except Exception:
            return None

    # ──────────────────────────────────────────────
    # Token 优化①：消息压缩
    # ──────────────────────────────────────────────

    def _compact_message(self, msg: Dict) -> Dict:
        """
        创建消息的紧凑副本，截断超长内容。
        仅影响 API 传参，不修改 self.messages 中的原始内容。
        """
        compact = dict(msg)
        role = msg.get("role", "")
        content = msg.get("content")

        if role == "tool" and content and len(content) > self.max_tool_output:
            compact["content"] = content[:self.max_tool_output] + "\n...[已截断]"
        elif role == "assistant" and content and len(content) > self.max_assistant_content:
            compact["content"] = content[:self.max_assistant_content] + "...[已截断]"

        return compact

    def _find_recent_boundary(self) -> int:
        """
        找到最近 keep_turns 轮对话的起始索引。
        以用户消息为轮次分隔符，确保工具调用链完整。

        Returns:
            消息列表中的起始索引
        """
        user_count = 0
        for i in range(len(self.messages) - 1, 0, -1):
            if self.messages[i].get("role") == "user":
                user_count += 1
                if user_count >= self.keep_turns:
                    return i
        return 1  # 不足 keep_turns 轮，保留全部（跳过系统消息）

    def _build_api_messages(self) -> List[Dict]:
        """
        构建发送给 API 的紧凑消息列表。

        结构：系统提示 → 记忆注入 → 历史摘要 → 最近N轮对话
        """
        result = []

        # 1. 系统提示词（始终第一）
        result.append(self.messages[0])

        # 2. 记忆注入（如有，独立于 self.messages）
        if self._memory_text:
            result.append({
                "role": "system",
                "content": f"【记忆参考】\n{self._memory_text}"
            })

        # 3. 历史摘要（如有，替代旧消息）
        if self._history_summary:
            result.append({
                "role": "system",
                "content": f"【历史摘要】\n{self._history_summary}"
            })

        # 4. 最近 N 轮对话（紧凑版，保留完整工具调用链）
        boundary = self._find_recent_boundary()
        for msg in self.messages[boundary:]:
            result.append(self._compact_message(msg))

        return result

    # ──────────────────────────────────────────────
    # Token 优化②：历史摘要
    # ──────────────────────────────────────────────

    def _messages_to_text(
        self, messages: List[Dict], max_per_msg: int = 500
    ) -> str:
        """
        将消息列表转为文本，用于摘要生成。
        每条消息截断到 max_per_msg 字符，避免摘要输入过长。

        Args:
            messages: 消息列表
            max_per_msg: 每条消息的最大字符数

        Returns:
            格式化的文本
        """
        lines = []
        for msg in messages:
            role = msg.get("role", "")
            content = msg.get("content", "")

            if role == "tool":
                truncated = content[:max_per_msg] + "..." if len(content) > max_per_msg else content
                lines.append(f"[工具结果]: {truncated}")
            elif role in ("user", "assistant") and content:
                truncated = content[:max_per_msg] + "..." if len(content) > max_per_msg else content
                lines.append(f"[{role.upper()}]: {truncated}")
            elif role == "assistant" and msg.get("tool_calls"):
                tc_names = [tc["function"]["name"] for tc in msg["tool_calls"]]
                lines.append(f"[ASSISTANT 调用工具]: {', '.join(tc_names)}")

        return "\n".join(lines)

    def _summarize_old_history(self):
        """
        将超出最近 keep_turns 轮的旧消息通过 LLM 生成摘要。

        摘要累积更新策略：
        已有摘要 + 新增旧消息 → LLM 合并为新摘要

        摘要完成后，旧消息从 self.messages 中移除，
        后续 API 调用只传摘要 + 最近 keep_turns 轮。
        """
        boundary = self._find_recent_boundary()

        # 旧消息 = 系统提示之后、最近 N 轮之前
        old_messages = self.messages[1:boundary]

        if not old_messages:
            return

        old_text = self._messages_to_text(old_messages, max_per_msg=300)

        if not old_text.strip():
            return

        # 如果已有摘要，融入新摘要
        existing = (
            f"已有摘要：{self._history_summary}\n\n"
            if self._history_summary else ""
        )

        try:
            cli, mdl = self._get_summarize_client()
            response = cli.chat.completions.create(
                model=mdl,
                messages=[
                    {"role": "system", "content": _HISTORY_SUMMARIZE_SYSTEM},
                    {"role": "user", "content": _HISTORY_SUMMARIZE_USER.format(
                        existing=existing, old_text=old_text)},
                ],
                temperature=0.1,
                max_tokens=300,
            )
            if isinstance(response.choices[0].message.content, str):
                self._history_summary = response.choices[0].message.content.strip()

            # 从 self.messages 中移除已摘要的旧消息
            self.messages = [self.messages[0]] + self.messages[boundary:]

            if self.tool_log:
                self.tool_log(
                    f"📝 历史摘要已更新，压缩 {len(old_messages)} 条消息"
                )
        except Exception as e:
            if self.tool_log:
                self.tool_log(f"⚠️ 摘要生成失败: {e}")

    # ──────────────────────────────────────────────
    # Token 优化③：记忆注入（独立于消息列表）
    # ──────────────────────────────────────────────

    def _inject_memories(self):
        """
        将重要记忆注入到上下文中。

        优化点：
        - 记忆文本存储在 _memory_text，不修改 self.messages
        - 由 _build_api_messages() 负责组装到 API 消息中
        - 条数从 15 (10+5) 降至 8 (5+3)
        """
        if not self.memory or self._memory_injected:
            return

        try:
            important = self.memory.get_important_memories(limit=5)
            recent = self.memory.get_recent_memories(limit=3)

            # 合并去重
            seen_ids = set()
            combined = []
            for m in important + recent:
                if m["id"] not in seen_ids:
                    seen_ids.add(m["id"])
                    combined.append(m)

            # 限制条数
            combined = combined[:self.memory_inject_limit]

            if not combined:
                self._memory_injected = True
                return

            self._memory_text = "\n".join(
                f"- [{m['category']}] {m['summary']}" for m in combined
            )

            self._memory_injected = True

            if self.tool_log:
                self.tool_log(f"🧠 已准备 {len(combined)} 条记忆注入")
        except Exception as e:
            if self.tool_log:
                self.tool_log(f"⚠️ 记忆注入失败: {e}")

    # ──────────────────────────────────────────────
    # Token 优化④：记忆提取（限窗 + 截断）
    # ──────────────────────────────────────────────

    def _extract_memories_from_conversation(self) -> List[Dict]:
        """
        使用 LLM 从最近 N 轮对话中提取记忆条目。

        优化点：
        - 只取最近 memory_extract_rounds 轮，不再发全量历史
        - 每条消息截断到 800 字符，避免摘要输入过长
        """
        if not self.memory:
            return []

        # 只取最近 memory_extract_rounds 轮对话
        chat_lines = []
        user_count = 0
        for msg in reversed(self.messages):
            role = msg.get("role", "")
            content = msg.get("content", "")
            if role == "user":
                user_count += 1
                if user_count > self.memory_extract_rounds:
                    break
            if role in ("user", "assistant") and content:
                # 截断长内容
                truncated = (
                    content[:800] + "..." if len(content) > 800 else content
                )
                chat_lines.append(f"[{role.upper()}]: {truncated}")

        chat_lines.reverse()
        chat_text = "\n".join(chat_lines)

        if not chat_text.strip():
            return []

        try:
            cli, mdl = self._get_summarize_client()
            response = cli.chat.completions.create(
                model=mdl,
                messages=[
                    {"role": "system", "content": _MEMORY_EXTRACT_SYSTEM},
                    {"role": "user", "content": _MEMORY_EXTRACT_USER_TEMPLATE.format(
                        chat_text=chat_text)},
                ],
                temperature=0.1,
                max_tokens=1024,
            )

            raw = response.choices[0].message.content.strip()

            # 清洗：去掉可能的 markdown 代码块包裹
            raw = re.sub(r"^```(?:json)?\s*", "", raw)
            raw = re.sub(r"\s*```$", "", raw)
            raw = raw.strip()

            # 尝试提取 JSON 数组
            json_match = re.search(r"\[.*\]", raw, re.DOTALL)
            if not json_match:
                if self.tool_log:
                    self.tool_log(f"⚠️ 记忆提取：未找到 JSON 数组，原始输出: {raw[:200]}")
                return []

            memories = json.loads(json_match.group())

            if not isinstance(memories, list):
                return []

            # 校验并规范化
            valid_categories = {
                "user_preference", "fact", "project_info", "decision",
                "experience", "code_pattern", "tool_usage", "environment", "general"
            }

            result = []
            for m in memories:
                if not isinstance(m, dict):
                    continue
                cat = m.get("category", "general")
                if cat not in valid_categories:
                    cat = "general"
                summary = m.get("summary", "").strip()
                if not summary:
                    continue
                importance = min(5, max(1, int(m.get("importance", 3))))
                tags = m.get("tags", [])
                if not isinstance(tags, list):
                    tags = []
                tags = [str(t).strip() for t in tags if str(t).strip()][:5]

                result.append({
                    "category": cat,
                    "summary": summary,
                    "importance": importance,
                    "tags": tags,
                })

            return result

        except json.JSONDecodeError as e:
            if self.tool_log:
                self.tool_log(f"⚠️ 记忆提取：JSON 解析失败: {e}")
            return []
        except Exception as e:
            if self.tool_log:
                self.tool_log(f"⚠️ 记忆提取失败: {e}")
            return []

    # ──────────────────────────────────────────────
    # 记忆保存
    # ──────────────────────────────────────────────

    def _save_conversation_memory(self):
        """
        在会话结束后，通过 LLM 提取并保存记忆。
        无需用户确认，自动执行。
        """
        if not self.memory:
            return

        # 消息太少则跳过
        msg_count = sum(
            1 for m in self.messages if m["role"] in ("user", "assistant"))
        if msg_count < self.memory_extract_threshold:
            return

        if self.tool_log:
            self.tool_log("🧠 开始 LLM 记忆提取...")

        memories = self._extract_memories_from_conversation()

        if not memories:
            if self.tool_log:
                self.tool_log("🧠 本次对话无值得记忆的内容")
            return

        saved_count = 0
        for m in memories:
            try:
                self.memory.add_memory(
                    summary=m["summary"],
                    category=m["category"],
                    importance=m["importance"],
                    tags=m["tags"],
                )
                saved_count += 1
                if self.tool_log:
                    self.tool_log(
                        f"💾 [{m['category']}] (重要度:{m['importance']}) {m['summary'][:100]}"
                    )
            except Exception as e:
                if self.tool_log:
                    self.tool_log(f"⚠️ 保存记忆失败: {e}")

        if self.tool_log:
            self.tool_log(f"🧠 记忆提取完成，共保存 {saved_count} 条")

    # ──────────────────────────────────────────────
    # Token 优化⑤：统一工具执行方法（消除冗余）
    # ──────────────────────────────────────────────

    def _execute_tool_call(self, call) -> Tuple[str, str, str]:
        """
        执行单个工具调用。

        Args:
            call: 工具调用对象（需有 .id, .function.name, .function.arguments）

        Returns:
            Tuple[str, str, str]: (call_id, func_name, result_string)
        """
        func_name = call.function.name
        call_id = call.id

        if func_name not in self.toolkit.func_map:
            err = f"错误：未知工具 {func_name}"
            self.add_tool_result(call_id, err)
            return call_id, func_name, err

        try:
            args = json.loads(call.function.arguments)
        except json.JSONDecodeError:
            err = "错误：参数解析失败"
            self.add_tool_result(call_id, err)
            return call_id, func_name, err

        if self.tool_log:
            self.tool_log(f"🔧 调用工具: {func_name}({args})")

        try:
            result = self.toolkit.func_map[func_name](**args)
            if self.tool_log:
                self.tool_log(f"✅ 结果: {result}")
        except Exception as e:
            result = f"工具执行错误: {e}"
            if self.tool_log:
                self.tool_log(f"❌ 错误: {e}")

        result_str = str(result)
        self.add_tool_result(call_id, result_str)
        return call_id, func_name, result_str

    # @2026-04-23 generated by unknown_model, 累积 token 用量
    def _accumulate_usage(self, usage):
        """从 API 响应中累积 token 用量"""
        if usage is None:
            return
        u = self._last_usage
        prompt = getattr(usage, 'prompt_tokens', None)
        completion = getattr(usage, 'completion_tokens', None)
        total = getattr(usage, 'total_tokens', None)
        if prompt:
            u["prompt_tokens"] += prompt
        if completion:
            u["completion_tokens"] += completion
        if total:
            u["total_tokens"] += total
        if u["total_tokens"] == 0 and u["prompt_tokens"] and u["completion_tokens"]:
            u["total_tokens"] = u["prompt_tokens"] + u["completion_tokens"]

    # ──────────────────────────────────────────────
    # 核心对话流程（Token 优化版 + rounds 收集 + token 统计）
    # ──────────────────────────────────────────────

    def chat_stream(self, msg: str, callback: Callable[[str], None]) -> Tuple[str, bool]:
        """
        流式对话，支持工具调用。

        Token 优化要点：
        - 使用 _build_api_messages() 构建紧凑消息，替代直接传 self.messages
        - 在循环前调用 _summarize_old_history() 摘要旧消息
        - 工具输出和助手回复在 API 传参时截断

        中间轮次收集：
        - chat_stream 期间，所有中间 request/response 收集到 _rounds_collector
        - 包括 assistant tool_calls、tool results、最终 assistant 文本回答
        - 流结束后由调用方通过 storage.update_msg_rounds() 一次性写入 conversations
        - 不包括初始 user message（已存储在 conversations.user_msg）

        Args:
            msg: 用户消息
            callback: 流式输出回调函数

        Returns:
            Tuple[str, bool]: (助手完整回复, 是否使用了工具调用)
        """
        self.reset_interrupt()

        # 重置轮次收集器和 token 统计
        self._rounds_collector = []
        self._last_usage = {"total_tokens": 0, "prompt_tokens": 0, "completion_tokens": 0}

        # 1. 注入记忆（仅第一次）
        self._inject_memories()

        # 2. 添加用户消息到完整历史
        self.add_user_message(msg)

        # 3. 摘要旧历史（在 API 循环前执行一次）
        self._summarize_old_history()

        full_reply = ""
        used_tools = False
        iterations = 0

        while iterations < self.max_iterations:
            if self.interrupted:
                self.add_assistant_message(full_reply + "\n[已打断]")
                # 收集打断时的最终 assistant 消息
                self._rounds_collector.append({
                    "role": "assistant",
                    "content": full_reply + "\n[已打断]",
                })
                return full_reply + "\n[已打断]", used_tools

            # ★ 核心优化：使用紧凑消息列表
            api_messages = self._build_api_messages()

            try:
                kwargs = {
                    "model": self.model,
                    "messages": api_messages,   # ← 紧凑消息
                    "tools": self.tools,
                    "tool_choice": "auto",
                    "stream": True,
                    # @2026-04-23 generated by unknown_model, 请求 stream 返回 usage
                    "stream_options": {"include_usage": True},
                }

                # @2026-04-19 generated by Pro/zai-org/GLM-5.1, thinking动态检测+降级重试
                # 首次调用时尝试带 thinking，若失败则自动降级;
                # 后续直接根据 _thinking_supported 决定是否传参
                should_try_thinking = (
                    self.enable_thinking
                    and self._thinking_supported is not False
                )
                if should_try_thinking:
                    kwargs["extra_body"] = {"thinking": {"type": "enabled"}}

                try:
                    response = self.client.chat.completions.create(**kwargs)
                    # 调用成功，确认支持 thinking
                    if should_try_thinking and self._thinking_supported is None:
                        self._thinking_supported = True
                        if self.tool_log:
                            self.tool_log("🧠 模型支持 thinking，已启用")
                except Exception as think_err:
                    # 判断是否为 thinking 不支持的错误
                    if should_try_thinking and self._thinking_supported is None:
                        err_str = str(think_err).lower()
                        if 'thinking' in err_str or 'extra_body' in err_str or 'unsupported' in err_str or 'invalid' in err_str:
                            # 降级：不带 thinking 重试
                            self._thinking_supported = False
                            if self.tool_log:
                                self.tool_log("⚠️ 模型不支持 thinking，已自动降级")
                            kwargs.pop("extra_body", None)
                            # 保留 stream_options 以维持 token 统计
                            # 若 API 严格不支持此参数，外层异常会捕获并提示
                            response = self.client.chat.completions.create(**kwargs)
                        else:
                            # 非 thinking 相关错误，向上抛出
                            raise
                    else:
                        raise
            except Exception as e:
                error_msg = f"API调用错误: {e}"
                callback(error_msg)
                self.add_assistant_message(full_reply + error_msg)
                # 收集 API 错误
                self._rounds_collector.append({
                    "role": "assistant",
                    "content": full_reply + error_msg,
                })
                return full_reply + error_msg, used_tools

            # 收集流式响应
            content_parts = []
            tool_calls_data = []

            for chunk in response:
                if self.interrupted:
                    break

                # @2026-04-23 generated by unknown_model, 累积 usage 信息
                if hasattr(chunk, 'usage') and chunk.usage:
                    self._accumulate_usage(chunk.usage)

                if not hasattr(chunk, 'choices') or not chunk.choices:
                    continue

                delta = chunk.choices[0].delta

                # 处理内容
                if delta.content:
                    content_parts.append(delta.content)
                    callback(delta.content)

                # 处理工具调用
                if delta.tool_calls:
                    for tc in delta.tool_calls:
                        idx = tc.index

                        # 扩展列表
                        while len(tool_calls_data) <= idx:
                            tool_calls_data.append({
                                "id": "",
                                "name": "",
                                "arguments": ""
                            })

                        if tc.id:
                            tool_calls_data[idx]["id"] = tc.id
                        if tc.function:
                            if tc.function.name:
                                tool_calls_data[idx]["name"] = tc.function.name
                            if tc.function.arguments:
                                tool_calls_data[idx]["arguments"] += tc.function.arguments

            # 合并内容
            content = "".join(content_parts)
            full_reply += content

            # 检查是否有完整的工具调用
            valid_tool_calls = []
            for tc_data in tool_calls_data:
                if tc_data["id"] and tc_data["name"]:
                    from types import SimpleNamespace
                    valid_tool_calls.append(SimpleNamespace(
                        id=tc_data["id"],
                        function=SimpleNamespace(
                            name=tc_data["name"],
                            arguments=tc_data["arguments"]
                        )
                    ))

            if valid_tool_calls:
                # 有工具调用
                used_tools = True

                # @2026-04-19 generated by Pro/zai-org/GLM-5.1, 收集 assistant tool_calls 到 rounds
                tc_list_for_collector = [{
                    "id": tc.id,
                    "type": "function",
                    "function": {
                        "name": tc.function.name,
                        "arguments": tc.function.arguments
                    }
                } for tc in valid_tool_calls]

                self._rounds_collector.append({
                    "role": "assistant",
                    "content": content if content else "",
                    "tool_calls": tc_list_for_collector,
                })

                # 1. 将助手包含 tool_calls 的消息存入完整历史
                self.messages.append({
                    "role": "assistant",
                    "content": content if content else None,
                    "tool_calls": [{
                        "id": tc.id,
                        "type": "function",
                        "function": {
                            "name": tc.function.name,
                            "arguments": tc.function.arguments
                        }
                    } for tc in valid_tool_calls]
                })

                # 2. 执行工具调用（使用统一方法）
                has_reload = any(
                    tc.function.name == "toolkit_reload"
                    for tc in valid_tool_calls
                )

                for call in valid_tool_calls:
                    call_id, func_name, result_str = self._execute_tool_call(call)

                    # @2026-04-19 generated by Pro/zai-org/GLM-5.1, 收集 tool result 到 rounds
                    self._rounds_collector.append({
                        "role": "tool",
                        "content": result_str,
                        "tool_call_id": call_id,
                    })

                # 3. 如果调用了 reload，则刷新本地工具定义
                if has_reload:
                    self._build_tools()

                iterations += 1

                # 4. 流式反馈
                if content:
                    callback(f"\n\n[正在执行工具，处理中...]\n\n")

                # 继续下一次循环
                continue

            elif content:
                # 没有工具调用，只有文本内容，视为最终回答
                self.add_assistant_message(content)

                # @2026-04-19 generated by Pro/zai-org/GLM-5.1, 收集最终 assistant 回答到 rounds
                self._rounds_collector.append({
                    "role": "assistant",
                    "content": content,
                })
                break
            else:
                # 既无工具也无内容
                break

        # 如果达到最大迭代次数
        if iterations >= self.max_iterations:
            warning = f"\n\n[警告：已达到最大迭代次数 {self.max_iterations}，对话强制终止]"
            callback(warning)
            full_reply += warning
            self.add_assistant_message(full_reply)

            # @2026-04-19 generated by Pro/zai-org/GLM-5.1, 收集迭代超限警告到 rounds
            self._rounds_collector.append({
                "role": "assistant",
                "content": full_reply,
            })

        # 自动提取并保存记忆
        self._save_conversation_memory()

        return full_reply, used_tools
