"""
存储模块
使用 SQLite 存储聊天历史、主题和 Agent 循环详情
"""

import sqlite3
import json
from typing import Dict, Optional, List, cast
import logging

logger = logging.getLogger("Storage")
class Storage:
    def __init__(self, db_path="chat_history.db"):
        logger.info(f"load database {db_path}")
        self.db_path = db_path
        self.conn = sqlite3.connect(db_path, check_same_thread=False)
        self.conn.row_factory = sqlite3.Row
        self._init_tables()
        self._migrate()

    def _init_tables(self):
        c = self.conn.cursor()
        c.execute('''
            CREATE TABLE IF NOT EXISTS topics (
                topic_id INTEGER PRIMARY KEY AUTOINCREMENT,
                title TEXT NOT NULL,
                create_stamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                last_update_stamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        ''')
        c.execute('''
            CREATE TABLE IF NOT EXISTS conversations (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                topic_id INTEGER NOT NULL,
                user_msg TEXT NOT NULL,
                ai_msg TEXT NOT NULL,
                is_func_calling INTEGER DEFAULT 0,
                stamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (topic_id) REFERENCES topics(topic_id)
            )
        ''')
        c.execute('''
            CREATE TABLE IF NOT EXISTS agent_rounds (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                conversation_id INTEGER NOT NULL,
                round_num INTEGER NOT NULL,
                role TEXT NOT NULL,
                content TEXT,
                tool_calls TEXT,
                tool_call_id TEXT,
                stamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (conversation_id) REFERENCES conversations(id)
            )
        ''')
        # @2026-04-23 generated by unknown_model, 新增 topic token 统计表
        c.execute('''
            CREATE TABLE IF NOT EXISTS topic_token_stats (
                topic_id INTEGER PRIMARY KEY,
                total_tokens INTEGER DEFAULT 0,
                total_prompt_tokens INTEGER DEFAULT 0,
                total_completion_tokens INTEGER DEFAULT 0,
                conversation_count INTEGER DEFAULT 0,
                last_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (topic_id) REFERENCES topics(topic_id)
            )
        ''')
        # @2026-04-27 generated by Gemini, 新增 topic 历史摘要表
        c.execute('''
            CREATE TABLE IF NOT EXISTS t_conv_summary (
                topic_id INTEGER PRIMARY KEY,
                summary TEXT NOT NULL,
                last_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (topic_id) REFERENCES topics(topic_id)
            )
        ''')
        self.conn.commit()
        c.close()

    # @2026-04-19 15:36:08 generated by Pro/zai-org/GLM-5.1, conversations表新增rounds_json列
    def _migrate(self):
        """数据库迁移：为新增字段做兼容处理"""
        c = self.conn.cursor()
        # 添加 rounds_json 列（如果不存在）
        try:
            c.execute("ALTER TABLE conversations ADD COLUMN rounds_json TEXT")
            self.conn.commit()
        except sqlite3.OperationalError:
            pass  # 列已存在
        c.close()

    def create_topic(self, title: str) -> int:
        c = self.conn.cursor()
        c.execute('INSERT INTO topics (title) VALUES (?)', (title,))
        self.conn.commit()
        tid = cast(int, c.lastrowid)
        c.close()
        return tid

    def update_topic_title(self, topic_id: int, new_title: str):
        """更新指定 topic 的标题"""
        c = self.conn.cursor()
        c.execute(
            'UPDATE topics SET title = ? WHERE topic_id = ?',
            (new_title, topic_id),
        )
        self.conn.commit()
        c.close()

    def update_topic_active(self, topic_id: int):
        c = self.conn.cursor()
        c.execute(
            'UPDATE topics SET last_update_stamp = CURRENT_TIMESTAMP WHERE topic_id = ?',
            (topic_id,),
        )
        self.conn.commit()
        c.close()

    # @2026-04-23 generated by unknown_model, 累加 topic token 消耗
    def add_topic_tokens(self, topic_id: int, total_tokens: int = 0, prompt_tokens: int = 0, completion_tokens: int = 0):
        """累加指定 topic 的 token 消耗"""
        if total_tokens == 0 and prompt_tokens == 0 and completion_tokens == 0:
            return
        c = self.conn.cursor()
        # 使用 INSERT OR UPDATE 模式
        c.execute('''
            INSERT INTO topic_token_stats (topic_id, total_tokens, total_prompt_tokens, total_completion_tokens, conversation_count)
            VALUES (?, ?, ?, ?, 1)
            ON CONFLICT(topic_id) DO UPDATE SET
                total_tokens = total_tokens + excluded.total_tokens,
                total_prompt_tokens = total_prompt_tokens + excluded.total_prompt_tokens,
                total_completion_tokens = total_completion_tokens + excluded.total_completion_tokens,
                conversation_count = conversation_count + 1,
                last_update = CURRENT_TIMESTAMP
        ''', (topic_id, total_tokens, prompt_tokens, completion_tokens))
        self.conn.commit()
        c.close()

    def get_topic_tokens(self, topic_id: int) -> Dict:
        """获取指定 topic 的 token 统计"""
        c = self.conn.cursor()
        c.execute('SELECT * FROM topic_token_stats WHERE topic_id = ?', (topic_id,))
        row = c.fetchone()
        c.close()
        if row:
            return dict(row)
        return {
            "topic_id": topic_id,
            "total_tokens": 0,
            "total_prompt_tokens": 0,
            "total_completion_tokens": 0,
            "conversation_count": 0,
        }

    def list_topics(self) -> List[Dict]:
        c = self.conn.cursor()
        c.execute('''
            SELECT t.*, 
                   COALESCE(s.total_tokens, 0) as total_tokens,
                   COALESCE(s.conversation_count, 0) as conversation_count
            FROM topics t
            LEFT JOIN topic_token_stats s ON t.topic_id = s.topic_id
            ORDER BY t.last_update_stamp DESC
        ''')
        rows = c.fetchall()
        c.close()
        return [dict(r) for r in rows]

    def save_msg(self, topic_id: int, user_msg: str, ai_msg: str, is_func: bool) -> int:
        c = self.conn.cursor()
        c.execute('''
            INSERT INTO conversations (topic_id, user_msg, ai_msg, is_func_calling)
            VALUES (?, ?, ?, ?)
        ''', (topic_id, user_msg, ai_msg, 1 if is_func else 0))
        conv_id = cast(int, c.lastrowid)
        self.conn.commit()
        c.close()
        self.update_topic_active(topic_id)
        return conv_id

    # @2026-04-19 15:36:08 generated by Pro/zai-org/GLM-5.1, 更新conversation的ai_msg和中间rounds
    def update_msg_rounds(
        self,
        conversation_id: int,
        ai_msg: str,
        is_func_calling: bool,
        rounds: Optional[List[Dict]] = None,
    ):
        """
        更新指定 conversation 行的 ai_msg、is_func_calling 和 rounds_json。

        在 chat_stream 完成后调用，将最终回复和中间工具调用链一次性写入。

        Args:
            conversation_id: conversations 表的行 ID
            ai_msg: AI 最终回复文本
            is_func_calling: 是否使用了工具调用
            rounds: 中间轮次列表（OpenAI API 消息格式）
                    [{"role":"assistant","content":"...","tool_calls":[...]},
                     {"role":"tool","content":"...","tool_call_id":"..."},
                     ...]
        """
        rounds_json = json.dumps(rounds, ensure_ascii=False) if rounds else None
        c = self.conn.cursor()
        c.execute('''
            UPDATE conversations
            SET ai_msg = ?, is_func_calling = ?, rounds_json = ?
            WHERE id = ?
        ''', (ai_msg, 1 if is_func_calling else 0, rounds_json, conversation_id))
        self.conn.commit()
        c.close()

    def save_agent_round(
        self,
        conversation_id: int,
        round_num: int,
        role: str,
        content: str,
        tool_calls: Optional[List[Dict]] = None,
        tool_call_id: Optional[str] = None,
    ):
        """保存 Agent 循环中的一轮请求/响应"""
        tc_json = json.dumps(
            tool_calls, ensure_ascii=False) if tool_calls else None
        c = self.conn.cursor()
        c.execute('''
            INSERT INTO agent_rounds (conversation_id, round_num, role, content, tool_calls, tool_call_id)
            VALUES (?, ?, ?, ?, ?, ?)
        ''', (conversation_id, round_num, role, content, tc_json, tool_call_id))
        self.conn.commit()
        c.close()

    def get_conversations(self, topic_id: int, limit: int = 5) -> List[Dict]:
        '''
        获取指定 topic 最近 N 轮对话（按时间倒序取最近 limit 条）
        解析 rounds_json 字段为 Python 对象（如果有）
        '''
        c = self.conn.cursor()
        c.execute(
            'SELECT * FROM conversations WHERE topic_id = ? ORDER BY stamp ASC', (topic_id,))
        rows = c.fetchall()
        c.close()
        if len(rows) >= limit:
            rows = rows[-limit:] ## 选择最新的 limit 条记录
        result = []
        for r in rows:
            d = dict(r)
            # @2026-04-19 15:36:08 generated by Pro/zai-org/GLM-5.1, 解析rounds_json为Python对象
            if d.get('rounds_json'):
                try:
                    d['rounds_json_parsed'] = json.loads(d['rounds_json'])
                except (json.JSONDecodeError, TypeError):
                    d['rounds_json_parsed'] = None
            else:
                d['rounds_json_parsed'] = None
            result.append(d)
        return result

    # @2026-04-19 generated by Pro/zai-org/GLM-5.1, 获取topic最近N轮对话用于生成摘要
    def get_recent_conversations(self, topic_id: int, limit: int = 3) -> List[Dict]:
        """获取指定 topic 最近 N 轮对话（按时间倒序取最近 limit 条，再反转为正序）"""
        c = self.conn.cursor()
        c.execute(
            'SELECT * FROM conversations WHERE topic_id = ? ORDER BY stamp DESC LIMIT ?',
            (topic_id, limit),
        )
        rows = c.fetchall()
        c.close()
        return [dict(r) for r in reversed(rows)]

    def get_topic(self, topic_id: int) -> Optional[Dict]:
        c = self.conn.cursor()
        c.execute('SELECT * FROM topics WHERE topic_id = ?', (topic_id,))
        r = c.fetchone()
        c.close()
        return dict(r) if r else None

    def get_agent_rounds(self, conversation_id: int) -> List[Dict]:
        """获取某个对话的所有 Agent 循环记录"""
        c = self.conn.cursor()
        c.execute(
            'SELECT * FROM agent_rounds WHERE conversation_id = ? ORDER BY id ASC',
            (conversation_id,),
        )
        rows = c.fetchall()
        c.close()
        result = []
        for r in rows:
            d = dict(r)
            if d.get('tool_calls'):
                d['tool_calls'] = json.loads(d['tool_calls'])
            result.append(d)
        return result

    # @2026-04-27 generated by Gemini, 历史摘要 CRUD
    def get_topic_summary(self, topic_id: int) -> Optional[str]:
        """获取指定 topic 的历史摘要"""
        c = self.conn.cursor()
        c.execute('SELECT summary FROM t_conv_summary WHERE topic_id = ?', (topic_id,))
        row = c.fetchone()
        c.close()
        return row['summary'] if row else None

    def update_topic_summary(self, topic_id: int, summary: str):
        """更新或插入指定 topic 的历史摘要"""
        c = self.conn.cursor()
        c.execute('''
            INSERT INTO t_conv_summary (topic_id, summary, last_update)
            VALUES (?, ?, CURRENT_TIMESTAMP)
            ON CONFLICT(topic_id) DO UPDATE SET
                summary = excluded.summary,
                last_update = CURRENT_TIMESTAMP
        ''', (topic_id, summary))
        self.conn.commit()
        c.close()
