"""
存储模块
使用 SQLite 存储聊天历史、主题、Agent 循环详情和长期记忆
"""

# NOTE: 2026-05-04 07:44:42, self-evolved by tea_agent --- 修改周轮转逻辑：从 rename(移动) 改为 copy2(复制)，使得新数据库保留所有历史记录而非空库
# NOTE: 2026-04-30 11:42:17, self-evolved by tea_agent --- 添加 os 和 datetime 导入
import os
import shutil
import sqlite3
import json
from datetime import datetime
from typing import Dict, Optional, List, cast
import logging

logger = logging.getLogger("Storage")
class Storage:
# NOTE: 2026-04-30 11:42:27, self-evolved by tea_agent --- __init__ 增加周轮转检查和周标识写入
    def __init__(self, db_path="chat_history.db"):
        self.db_path = db_path
        self._maybe_rotate_db()  # NOTE: 每周轮转检查，在连接前执行
        logger.info(f"load database {db_path}")
# NOTE: 2026-05-01 11:43:23, self-evolved by tea_agent --- 启用WAL模式，确保跨线程写入后主线程立即可读
        self.conn = sqlite3.connect(db_path, check_same_thread=False)
        self.conn.row_factory = sqlite3.Row
        # 启用 WAL 模式，跨线程写入立即可见
# NOTE: 2026-05-09 19:59:07, self-evolved by tea_agent --- Storage.__init__: 创建 .protected 标记文件，防止 Agent 误删数据库
        self.conn.execute("PRAGMA journal_mode=WAL")
        self._init_tables()
        self._migrate()
        self._write_week_key()  # NOTE: 写入本周 ISO 周标识
        self._auto_backup()     # NOTE: 启动时自动备份数据库
        self._protect_db()      # NOTE: 创建保护标记，防止误删

        # @2026-04-29 gen by deepseek-v4-pro, 新增memories表及8个CRUD方法
# NOTE: 2026-04-30 11:42:35, self-evolved by tea_agent --- _init_tables 新增 _meta 元数据表
    def _init_tables(self):
        c = self.conn.cursor()
        c.execute('''
            CREATE TABLE IF NOT EXISTS _meta (
                key TEXT PRIMARY KEY,
                value TEXT
            )
        ''')
        c.execute('''
            CREATE TABLE IF NOT EXISTS topics (
                topic_id INTEGER PRIMARY KEY AUTOINCREMENT,
                title TEXT NOT NULL,
                create_stamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                last_update_stamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        ''')
        c.execute('''
            CREATE TABLE IF NOT EXISTS conversations (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                topic_id INTEGER NOT NULL,
                user_msg TEXT NOT NULL,
                ai_msg TEXT NOT NULL,
                is_func_calling INTEGER DEFAULT 0,
                is_summarized INTEGER DEFAULT 0,
                stamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (topic_id) REFERENCES topics(topic_id)
            )
        ''')
        c.execute('''
            CREATE TABLE IF NOT EXISTS agent_rounds (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                conversation_id INTEGER NOT NULL,
                round_num INTEGER NOT NULL,
                role TEXT NOT NULL,
                content TEXT,
                tool_calls TEXT,
                tool_call_id TEXT,
                stamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (conversation_id) REFERENCES conversations(id)
            )
        ''')
        # @2026-04-23 generated by unknown_model, 新增 topic token 统计表
        c.execute('''
            CREATE TABLE IF NOT EXISTS topic_token_stats (
                topic_id INTEGER PRIMARY KEY,
                total_tokens INTEGER DEFAULT 0,
                total_prompt_tokens INTEGER DEFAULT 0,
                total_completion_tokens INTEGER DEFAULT 0,
                conversation_count INTEGER DEFAULT 0,
                last_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (topic_id) REFERENCES topics(topic_id)
            )
        ''')
        # @2026-04-27 generated by Gemini, 新增 topic 历史摘要表
        c.execute('''
            CREATE TABLE IF NOT EXISTS t_conv_summary (
                topic_id INTEGER PRIMARY KEY,
                summary TEXT NOT NULL,
                last_summarized_id INTEGER,
                last_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (topic_id) REFERENCES topics(topic_id)
            )
        ''')
# NOTE: 2026-04-30 16:13:34, self-evolved by tea_agent --- _init_tables新增3张表：system_prompts、reflections、config_history，支持反思/多版本提示词/配置变更追踪
        # @2026-04-29 generated by claude-agent, 新增长期记忆表
        c.execute('''
            CREATE TABLE IF NOT EXISTS memories (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                content TEXT NOT NULL,
                category TEXT NOT NULL DEFAULT 'general',
                priority INTEGER NOT NULL DEFAULT 2,
                importance INTEGER NOT NULL DEFAULT 3,
                expires_at TEXT,
                is_active INTEGER NOT NULL DEFAULT 1,
                tags TEXT DEFAULT '',
                source_topic_id INTEGER,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                last_accessed_at TIMESTAMP,
                FOREIGN KEY (source_topic_id) REFERENCES topics(topic_id)
            )
        ''')
        # 2026-04-30 gen by deepseek-v4-pro, 系统提示词版本表（支持多版本演进）
        c.execute('''
            CREATE TABLE IF NOT EXISTS system_prompts (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                version TEXT NOT NULL,
                content TEXT NOT NULL,
                reason TEXT DEFAULT '',
                source_reflection_id INTEGER,
                is_active INTEGER DEFAULT 1,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        ''')
        # 2026-04-30 gen by deepseek-v4-pro, 反思记录表（元认知）
        c.execute('''
            CREATE TABLE IF NOT EXISTS reflections (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                topic_id INTEGER,
                summary TEXT NOT NULL,
                details TEXT DEFAULT '',
                tool_stats TEXT DEFAULT '{}',
                suggestions TEXT DEFAULT '[]',
                is_applied INTEGER DEFAULT 0,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (topic_id) REFERENCES topics(topic_id)
            )
        ''')
# NOTE: 2026-05-06 19:16:44, self-evolved by tea_agent --- _init_tables 新增 msg_vectors 表用于存储用户消息的文本向量
        # 2026-04-30 gen by deepseek-v4-pro, 配置变更历史表（自我调优追踪）
        c.execute('''
            CREATE TABLE IF NOT EXISTS config_history (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                key TEXT NOT NULL,
                old_value TEXT,
                new_value TEXT NOT NULL,
                reason TEXT DEFAULT '',
                source_reflection_id INTEGER,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        ''')
# NOTE: 2026-05-07 07:35:36, self-evolved by tea_agent --- msg_vectors 表 embedding 列从 TEXT 改为 BLOB（numpy float32 tobytes），含迁移
        # 2026-05-06 gen by claude, 消息文本向量表（用于语义搜索）
        # 2026-05-07: embedding 列从 TEXT(JSON) 改为 BLOB(numpy float32 tobytes)
        self._migrate_msg_vectors(c)
        c.execute('''
            CREATE TABLE IF NOT EXISTS msg_vectors (
                conversation_id INTEGER PRIMARY KEY,
                embedding BLOB NOT NULL,
                dimension INTEGER DEFAULT 0,
                model_name TEXT DEFAULT '',
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE
            )
        ''')
        self.conn.commit()
        c.close()

    def _migrate_msg_vectors(self, c):
        """迁移 msg_vectors 表：TEXT→BLOB（若已存在旧格式则重建）"""
        import logging
        log = logging.getLogger("Store")
        c.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='msg_vectors'")
        if not c.fetchone():
            return  # 表不存在，无需迁移
        # 检查 embedding 列类型
        c.execute("PRAGMA table_info(msg_vectors)")
        cols = {row[1]: row[2] for row in c.fetchall()}
        if cols.get("embedding", "").upper() == "BLOB":
            return  # 已是 BLOB 格式
        log.info("msg_vectors 表从 TEXT 迁移到 BLOB 格式，旧数据将被丢弃（需重新生成向量）")
        c.execute("DROP TABLE IF EXISTS msg_vectors")
        self.conn.commit()

    # @2026-04-19 15:36:08 generated by Pro/zai-org/GLM-5.1, conversations表新增rounds_json列
    def _migrate(self):
        """数据库迁移：为新增字段做兼容处理"""
        c = self.conn.cursor()
        # 添加 rounds_json 列（如果不存在）
        try:
            c.execute("ALTER TABLE conversations ADD COLUMN rounds_json TEXT")
            self.conn.commit()
        except sqlite3.OperationalError:
            pass  # 列已存在

# NOTE: 2026-04-30 09:24:44, self-evolved by tea_agent --- topic_token_stats表增加便宜模型token列，add_topic_tokens支持便宜模型参数
        # @2026-04-28 generated by Gemini, 添加 is_summarized 列
        try:
            c.execute("ALTER TABLE conversations ADD COLUMN is_summarized INTEGER DEFAULT 0")
            self.conn.commit()
        except sqlite3.OperationalError:
            pass

        # @2026-04-28 generated by Gemini, 为 t_conv_summary 添加 last_summarized_id 列
        try:
            c.execute("ALTER TABLE t_conv_summary ADD COLUMN last_summarized_id INTEGER")
            self.conn.commit()
        except sqlite3.OperationalError:
            pass

# NOTE: 2026-04-30 09:18:00, self-evolved by tea_agent --- topic_token_stats增加便宜模型token列
# NOTE: 2026-05-07 13:12:39, self-evolved by tea_agent --- _migrate 新增嵌入模型 token 列（total_embedding_tokens/prompt_tokens）
        for col, col_type in [
            ("total_cheap_tokens", "INTEGER DEFAULT 0"),
            ("total_cheap_prompt_tokens", "INTEGER DEFAULT 0"),
            ("total_cheap_completion_tokens", "INTEGER DEFAULT 0"),
        ]:
            try:
                c.execute(f"ALTER TABLE topic_token_stats ADD COLUMN {col} {col_type}")
                self.conn.commit()
            except sqlite3.OperationalError:
                pass

        # 嵌入模型 token 列
        for col, col_type in [
            ("total_embedding_tokens", "INTEGER DEFAULT 0"),
            ("total_embedding_prompt_tokens", "INTEGER DEFAULT 0"),
        ]:
            try:
                c.execute(f"ALTER TABLE topic_token_stats ADD COLUMN {col} {col_type}")
                self.conn.commit()
            except sqlite3.OperationalError:
                pass

# NOTE: 2026-04-30 11:42:58, self-evolved by tea_agent --- 新增 _get_week_key、_maybe_rotate_db、_write_week_key 三个方法
        c.close()

    # NOTE: 2026-04-30 11:42:44, self-evolved by tea_agent --- 每周db轮转：_get_week_key、_maybe_rotate_db、_write_week_key
    @staticmethod
    def _get_week_key():
        """返回当前 ISO 周标识，如 '2026-W18'"""
        return datetime.now().strftime("%G-W%V")

# NOTE: 2026-05-04 07:45:09, self-evolved by tea_agent --- 更新 _maybe_rotate_db 方法的 docstring：从"重命名"改为"复制"
    def _maybe_rotate_db(self):
        """
        如果 chat_history.db 属于上一周，则复制为 chat_history_{yyyy-mm-dd}.db 归档。
        保留原 db 不变（含全部历史），只更新 week_key。
        必须在数据库连接之前调用。
        """
        if not os.path.exists(self.db_path):
            return  # 首次运行，无需轮转

        # 读取旧 db 中存储的周标识
        db_week = None
        try:
            tmp_conn = sqlite3.connect(self.db_path)
            c = tmp_conn.cursor()
            c.execute("SELECT value FROM _meta WHERE key = 'week_key'")
            row = c.fetchone()
            db_week = row[0] if row else None
            tmp_conn.close()
        except sqlite3.OperationalError:
            pass  # _meta 表不存在（旧版 db），也视为需要轮转

        current_week = self._get_week_key()
        if db_week == current_week:
            return  # 同一周，无需轮转

# NOTE: 2026-04-30 11:44:29, self-evolved by tea_agent --- 修复归档文件名缺少目录路径的 bug
# NOTE: 2026-04-30 11:46:46, self-evolved by tea_agent --- _maybe_rotate_db 增加锁竞争容错，失败时仅警告不崩溃
# NOTE: 2026-05-04 07:45:16, self-evolved by tea_agent --- 更新方法内注释：从"重命名旧db"改为"复制旧db做归档"
        # 需要轮转：复制旧 db 做归档（保持在同一目录），原 db 保留全部历史
        db_dir = os.path.dirname(self.db_path) or "."
        archive_name = os.path.join(db_dir, f"chat_history_{datetime.now().strftime('%Y-%m-%d')}.db")
        # 如果归档文件已存在，追加时间戳避免覆盖
        if os.path.exists(archive_name):
            archive_name = os.path.join(db_dir, f"chat_history_{datetime.now().strftime('%Y-%m-%d_%H%M%S')}.db")
# NOTE: 2026-05-04 07:44:53, self-evolved by tea_agent --- _maybe_rotate_db 中 os.rename 改为 shutil.copy2：归档时复制而非移动，新db保留全部历史
        try:
            shutil.copy2(self.db_path, archive_name)
            logger.info(f"归档旧数据库: {self.db_path} -> {archive_name} (保留历史记录)")
        except OSError as e:
            logger.warning(
                f"无法归档旧数据库（文件可能被占用）: {e}。"
                f"将继续使用当前 db，下次启动时重试轮转。"
            )

    def _write_week_key(self):
        """在 _meta 表中记录本周标识"""
        c = self.conn.cursor()
        c.execute(
            "INSERT OR REPLACE INTO _meta (key, value) VALUES ('week_key', ?)",
            (self._get_week_key(),),
        )
        self.conn.commit()
        c.close()

    def create_topic(self, title: str) -> int:
        c = self.conn.cursor()
        c.execute('INSERT INTO topics (title) VALUES (?)', (title,))
        self.conn.commit()
        tid = cast(int, c.lastrowid)
        c.close()
        return tid

# NOTE: 2026-05-02 18:31:06, self-evolved by tea_agent --- store.py update_topic_title 保护 chat_room_* 主题标题不可被修改
# NOTE: 2026-05-02 18:31:24, self-evolved by tea_agent --- 修复 update_topic_title：用 self.get_topic 替代不存在的 get_topic_title
    def update_topic_title(self, topic_id: int, new_title: str):
        """更新指定 topic 的标题（chat_room_* 前缀的主题受保护，不可修改）"""
        # 保护 chat_room 主题
        old = self.get_topic(topic_id)
        if old and (old.get("title") or "").startswith("chat_room_"):
            logger.debug(f"拒绝修改 chat_room 主题标题: {old['title']}")
            return
        c = self.conn.cursor()
        c.execute(
            'UPDATE topics SET title = ? WHERE topic_id = ?',
            (new_title, topic_id),
        )
        self.conn.commit()
        c.close()

    def update_topic_active(self, topic_id: int):
        c = self.conn.cursor()
        c.execute(
            'UPDATE topics SET last_update_stamp = CURRENT_TIMESTAMP WHERE topic_id = ?',
            (topic_id,),
        )
        self.conn.commit()
        c.close()

    # @2026-04-29 gen by deepseek-v4-pro, 硬删除主题及关联数据
    def delete_topic(self, topic_id: int):
        """
        硬删除主题及其所有关联数据。
        包括：conversations、agent_rounds、token_stats、摘要。
        此操作不可撤销。
        """
        c = self.conn.cursor()
        # 删除 agent_rounds（通过 conversation_id 关联）
        c.execute(
            "DELETE FROM agent_rounds WHERE conversation_id IN (SELECT id FROM conversations WHERE topic_id = ?)",
            (topic_id,),
        )
        # 删除 conversations
        c.execute("DELETE FROM conversations WHERE topic_id = ?", (topic_id,))
        # 删除 topic_token_stats
        c.execute("DELETE FROM topic_token_stats WHERE topic_id = ?", (topic_id,))
        # 删除 t_conv_summary
        c.execute("DELETE FROM t_conv_summary WHERE topic_id = ?", (topic_id,))
        # 删除 topic 本身
        c.execute("DELETE FROM topics WHERE topic_id = ?", (topic_id,))
        self.conn.commit()
        c.close()

    # @2026-04-23 generated by unknown_model, 累加 topic token 消耗
# NOTE: 2026-04-30 09:25:12, self-evolved by tea_agent --- add_topic_tokens增加便宜模型参数(cheap_tokens/cheap_prompt_tokens/cheap_completion_tokens)
# NOTE: 2026-04-30 09:24:44, self-evolved by tea_agent --- add_topic_tokens支持便宜模型四个参数
# NOTE: 2026-05-07 13:13:09, self-evolved by tea_agent --- add_topic_tokens 新增嵌入模型参数 embedding_tokens/embedding_prompt_tokens
    def add_topic_tokens(
        self, topic_id: int,
        total_tokens: int = 0, prompt_tokens: int = 0, completion_tokens: int = 0,
        cheap_tokens: int = 0, cheap_prompt_tokens: int = 0, cheap_completion_tokens: int = 0,
        embedding_tokens: int = 0, embedding_prompt_tokens: int = 0,
    ):
        """累加指定 topic 的 token 消耗（支持主模型+便宜模型+嵌入模型）"""
        has_main = total_tokens > 0 or prompt_tokens > 0 or completion_tokens > 0
        has_cheap = cheap_tokens > 0 or cheap_prompt_tokens > 0 or cheap_completion_tokens > 0
        has_embedding = embedding_tokens > 0 or embedding_prompt_tokens > 0
        if not has_main and not has_cheap and not has_embedding:
            return
        c = self.conn.cursor()
        # 使用 INSERT OR UPDATE 模式
        c.execute('''
            INSERT INTO topic_token_stats (
                topic_id, total_tokens, total_prompt_tokens, total_completion_tokens,
                total_cheap_tokens, total_cheap_prompt_tokens, total_cheap_completion_tokens,
                total_embedding_tokens, total_embedding_prompt_tokens,
                conversation_count
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 1)
            ON CONFLICT(topic_id) DO UPDATE SET
                total_tokens = total_tokens + excluded.total_tokens,
                total_prompt_tokens = total_prompt_tokens + excluded.total_prompt_tokens,
                total_completion_tokens = total_completion_tokens + excluded.total_completion_tokens,
                total_cheap_tokens = total_cheap_tokens + excluded.total_cheap_tokens,
                total_cheap_prompt_tokens = total_cheap_prompt_tokens + excluded.total_cheap_prompt_tokens,
                total_cheap_completion_tokens = total_cheap_completion_tokens + excluded.total_cheap_completion_tokens,
                total_embedding_tokens = total_embedding_tokens + excluded.total_embedding_tokens,
                total_embedding_prompt_tokens = total_embedding_prompt_tokens + excluded.total_embedding_prompt_tokens,
                conversation_count = conversation_count + 1,
                last_update = CURRENT_TIMESTAMP
        ''', (topic_id, total_tokens, prompt_tokens, completion_tokens,
              cheap_tokens, cheap_prompt_tokens, cheap_completion_tokens,
              embedding_tokens, embedding_prompt_tokens))
        self.conn.commit()
        c.close()

    def get_topic_tokens(self, topic_id: int) -> Dict:
        """获取指定 topic 的 token 统计"""
        c = self.conn.cursor()
        c.execute('SELECT * FROM topic_token_stats WHERE topic_id = ?', (topic_id,))
        row = c.fetchone()
        c.close()
        if row:
            return dict(row)
# NOTE: 2026-04-30 09:25:25, self-evolved by tea_agent --- get_topic_tokens默认返回值增加便宜模型字段
# NOTE: 2026-05-07 13:13:18, self-evolved by tea_agent --- get_topic_tokens 默认返回值增加嵌入模型字段
        return {
            "topic_id": topic_id,
            "total_tokens": 0,
            "total_prompt_tokens": 0,
            "total_completion_tokens": 0,
            "total_cheap_tokens": 0,
            "total_cheap_prompt_tokens": 0,
            "total_cheap_completion_tokens": 0,
            "total_embedding_tokens": 0,
            "total_embedding_prompt_tokens": 0,
            "conversation_count": 0,
        }

    def list_topics(self) -> List[Dict]:
        c = self.conn.cursor()
        c.execute('''
            SELECT t.*, 
                   COALESCE(s.total_tokens, 0) as total_tokens,
                   COALESCE(s.conversation_count, 0) as conversation_count
            FROM topics t
            LEFT JOIN topic_token_stats s ON t.topic_id = s.topic_id
            ORDER BY t.last_update_stamp DESC
        ''')
        rows = c.fetchall()
        c.close()
        return [dict(r) for r in rows]

# NOTE: 2026-05-07 07:45:00, self-evolved by tea_agent --- save_msg 新增自动嵌入钩子：每条 user_msg 保存后后台线程自动生成向量
    def save_msg(self, topic_id: int, user_msg: str, ai_msg: str, is_func: bool) -> int:
        '''
        新增一条，返回conversation_id，会话完成后，调用 update_msg_rounds() 更新。

        若 user_msg 非空且嵌入引擎已配置，自动后台生成文本向量存入 msg_vectors。
        '''
        c = self.conn.cursor()
        c.execute('''
            INSERT INTO conversations (topic_id, user_msg, ai_msg, is_func_calling)
            VALUES (?, ?, ?, ?)
        ''', (topic_id, user_msg, ai_msg, 1 if is_func else 0))
        conv_id = cast(int, c.lastrowid)
        self.conn.commit()
        c.close()
        self.update_topic_active(topic_id)

        # 自动嵌入：后台线程非阻塞生成 user_msg 向量
        if user_msg and user_msg.strip():
            self._auto_embed_async(conv_id, user_msg.strip())

        return conv_id

# NOTE: 2026-05-07 07:46:43, self-evolved by tea_agent --- _auto_embed_async 简化：去掉无效 mode=="none" 检查，embed() 自带 TF-IDF 回退
    def _auto_embed_async(self, conv_id: int, text: str):
        """后台线程自动生成并存储文本向量（fire-and-forget，不阻塞主流程）"""
        import threading

# NOTE: 2026-05-07 08:05:56, self-evolved by tea_agent --- _auto_embed_async except Exception: pass 改为 logger.warning，打印嵌入失败原因
        def _run():
            try:
                from tea_agent.embedding_util import get_embedding_engine
                engine = get_embedding_engine()
                vec = engine.embed(text)
                if vec:
                    self.store_embedding(conv_id, vec, engine.model_name, len(vec))
            except Exception as e:
                # 嵌入失败不影响对话流程，记录原因
                import logging
                logging.getLogger("store").warning(f"自动嵌入失败 (conv_id={conv_id}): {e}")

        t = threading.Thread(target=_run, daemon=True, name=f"auto-embed-{conv_id}")
        t.start()

    # @2026-04-19 15:36:08 generated by Pro/zai-org/GLM-5.1, 更新conversation的ai_msg和中间rounds
    def update_msg_rounds(
        self,
        conversation_id: int,
        ai_msg: str,
        is_func_calling: bool,
        rounds: Optional[List[Dict]] = None,
    ):
        """
        更新指定 conversation 行的 ai_msg、is_func_calling 和 rounds_json。

        在 chat_stream 完成后调用，将最终回复和中间工具调用链一次性写入。

        Args:
            conversation_id: conversations 表的行 ID
            ai_msg: AI 最终回复文本
            is_func_calling: 是否使用了工具调用
            rounds: 中间轮次列表（OpenAI API 消息格式）
                    [{"role":"assistant","content":"...","tool_calls":[...]},
                     {"role":"tool","content":"...","tool_call_id":"..."},
                     ...]
        """
        rounds_json = json.dumps(rounds, ensure_ascii=False) if rounds else None
        c = self.conn.cursor()
        c.execute('''
            UPDATE conversations
            SET ai_msg = ?, is_func_calling = ?, rounds_json = ?
            WHERE id = ?
        ''', (ai_msg, 1 if is_func_calling else 0, rounds_json, conversation_id))
        self.conn.commit()
        c.close()

    def save_agent_round(
        self,
        conversation_id: int,
        round_num: int,
        role: str,
        content: str,
        tool_calls: Optional[List[Dict]] = None,
        tool_call_id: Optional[str] = None,
    ):
        """保存 Agent 循环中的一轮请求/响应"""
        tc_json = json.dumps(
            tool_calls, ensure_ascii=False) if tool_calls else None
        c = self.conn.cursor()
        c.execute('''
            INSERT INTO agent_rounds (conversation_id, round_num, role, content, tool_calls, tool_call_id)
            VALUES (?, ?, ?, ?, ?, ?)
        ''', (conversation_id, round_num, role, content, tc_json, tool_call_id))
        self.conn.commit()
        c.close()

# NOTE: 2026-04-30 10:01:51, self-evolved by tea_agent --- get_conversations支持limit=-1返回全部记录
# NOTE: 2026-04-30 10:25:19, self-evolved by tea_agent --- get_conversations增加include_rounds参数，False时跳过rounds_json加载和解析
    def get_conversations(self, topic_id: int, limit: int = 5, include_rounds: bool = True) -> List[Dict]:
        '''
        获取指定 topic 最近 N 轮对话（按时间正序）。
        limit=-1 时返回全部记录。
        include_rounds=False 时跳过 rounds_json 加载和解析（轻量模式，加速加载）。

        Args:
            topic_id: 主题ID
            limit: 返回数量上限，-1=全部
            include_rounds: 是否加载并解析 rounds_json 列

        Returns:
            对话记录列表，每项含 id, user_msg, ai_msg, is_func_calling, stamp
            (include_rounds=True 时还含 rounds_json, rounds_json_parsed)
        '''
        c = self.conn.cursor()
        if include_rounds:
            c.execute(
                'SELECT * FROM conversations WHERE topic_id = ? ORDER BY stamp ASC', (topic_id,))
        else:
            c.execute(
                'SELECT id, topic_id, user_msg, ai_msg, is_func_calling, is_summarized, stamp '
                'FROM conversations WHERE topic_id = ? ORDER BY stamp ASC', (topic_id,))
        rows = c.fetchall()
        c.close()
        if limit == 0:
            return []  # limit=0 语义：返回 0 条
        if limit > 0 and len(rows) > limit:
            rows = rows[-limit:]  ## 选择最新的 limit 条记录
        result = []
        for r in rows:
            d = dict(r)
            if include_rounds:
                if d.get('rounds_json'):
                    try:
                        d['rounds_json_parsed'] = json.loads(d['rounds_json'])
                    except (json.JSONDecodeError, TypeError):
                        d['rounds_json_parsed'] = None
                else:
                    d['rounds_json_parsed'] = None
            result.append(d)
        return result

    # @2026-04-19 generated by Pro/zai-org/GLM-5.1, 获取topic最近N轮对话用于生成摘要
    def get_recent_conversations(self, topic_id: int, limit: int = 3) -> List[Dict]:
        """获取指定 topic 最近 N 轮对话（按时间倒序取最近 limit 条，再反转为正序）"""
        c = self.conn.cursor()
        c.execute(
            'SELECT * FROM conversations WHERE topic_id = ? ORDER BY stamp DESC LIMIT ?',
            (topic_id, limit),
        )
        rows = c.fetchall()
        c.close()
        return [dict(r) for r in reversed(rows)]

    def get_topic(self, topic_id: int) -> Optional[Dict]:
        c = self.conn.cursor()
        c.execute('SELECT * FROM topics WHERE topic_id = ?', (topic_id,))
        r = c.fetchone()
        c.close()
        return dict(r) if r else None

    def get_agent_rounds(self, conversation_id: int) -> List[Dict]:
        """获取某个对话的所有 Agent 循环记录"""
        c = self.conn.cursor()
        c.execute(
            'SELECT * FROM agent_rounds WHERE conversation_id = ? ORDER BY id ASC',
            (conversation_id,),
        )
        rows = c.fetchall()
        c.close()
        result = []
        for r in rows:
            d = dict(r)
            if d.get('tool_calls'):
                d['tool_calls'] = json.loads(d['tool_calls'])
            result.append(d)
        return result

    # @2026-04-27 generated by Gemini, 历史摘要 CRUD
    def get_topic_summary(self, topic_id: int) -> Optional[str]:
        """获取指定 topic 的历史摘要"""
        c = self.conn.cursor()
        c.execute('SELECT summary FROM t_conv_summary WHERE topic_id = ?', (topic_id,))
        row = c.fetchone()
        c.close()
        return row['summary'] if row else None

    def update_topic_summary(self, topic_id: int, summary: str, last_summarized_id: Optional[int] = None):
        """更新或插入指定 topic 的历史摘要"""
        c = self.conn.cursor()
        if last_summarized_id is not None:
            c.execute('''
                INSERT INTO t_conv_summary (topic_id, summary, last_summarized_id, last_update)
                VALUES (?, ?, ?, CURRENT_TIMESTAMP)
                ON CONFLICT(topic_id) DO UPDATE SET
                    summary = excluded.summary,
                    last_summarized_id = excluded.last_summarized_id,
                    last_update = CURRENT_TIMESTAMP
            ''', (topic_id, summary, last_summarized_id))
        else:
            c.execute('''
                INSERT INTO t_conv_summary (topic_id, summary, last_update)
                VALUES (?, ?, CURRENT_TIMESTAMP)
                ON CONFLICT(topic_id) DO UPDATE SET
                    summary = excluded.summary,
                    last_update = CURRENT_TIMESTAMP
            ''', (topic_id, summary))
        self.conn.commit()
        c.close()

    def mark_as_summarized(self, conversation_id: int):
        """将指定对话标记为已摘要"""
        c = self.conn.cursor()
        c.execute('UPDATE conversations SET is_summarized = 1 WHERE id = ?', (conversation_id,))
        self.conn.commit()
        c.close()

# NOTE: 2026-04-30 09:47:45, self-evolved by tea_agent --- get_unsummarized_conversations默认limit从-1(全部)改为50，防止无限制加载
    def get_unsummarized_conversations(self, topic_id: int, limit:int=50) -> List[Dict]:
        """获取指定 topic 中尚未摘要的所有对话"""
        c = self.conn.cursor()
        if limit < 0:
            c.execute('''
                SELECT * FROM conversations 
                WHERE topic_id = ? AND is_summarized = 0 
                ORDER BY stamp ASC
            ''', (topic_id,))
        else:
            c.execute('''
                SELECT * FROM conversations 
                WHERE topic_id = ? AND is_summarized = 0 
                ORDER BY stamp ASC LIMIT ?
            ''', (topic_id, limit))
        rows = c.fetchall()
        c.close()
        
        result = []
        for r in rows:
            d = dict(r)
            if d.get('rounds_json'):
                try:
                    d['rounds_json_parsed'] = json.loads(d['rounds_json'])
                except (json.JSONDecodeError, TypeError):
                    d['rounds_json_parsed'] = None
            else:
                d['rounds_json_parsed'] = None
            result.append(d)
        return result

    # ============================================================
    # @2026-04-29 generated by claude-agent, 长期记忆 (Memory) CRUD
    # ============================================================

# NOTE: 2026-05-02 12:05:07, self-evolved by tea_agent --- add_memory 新增 CRITICAL FIFO 淘汰：超过15条时软删除最旧的
    def add_memory(
        self,
        content: str,
        category: str = "general",
        priority: int = 2,
        importance: int = 3,
        expires_at: Optional[str] = None,
        tags: str = "",
        source_topic_id: Optional[int] = None,
    ) -> int:
        """
        添加一条记忆。

        Args:
            content: 记忆内容（精简摘要）
            category: 分类 (instruction/preference/fact/reminder/general)
            priority: 优先级 0=CRITICAL(有效指令) 1=HIGH 2=MEDIUM 3=LOW
            importance: 重要度 1-5
            expires_at: 过期时间 ISO datetime，None=永不过期
            tags: 逗号分隔标签
            source_topic_id: 来源会话 ID

        Returns:
            新记忆的 ID
        """
        # NOTE: 2026-05-02, self-evolved by tea_agent ---
        # CRITICAL 记忆上限 15 条，超出时 FIFO 淘汰最旧的（软删除）
        if priority == 0:
            self._enforce_critical_limit(max_critical=15)

        c = self.conn.cursor()
        c.execute('''
            INSERT INTO memories (content, category, priority, importance, 
                                  expires_at, tags, source_topic_id)
            VALUES (?, ?, ?, ?, ?, ?, ?)
        ''', (content, category, priority, importance, expires_at, tags, source_topic_id))
        self.conn.commit()
        mid = cast(int, c.lastrowid)
        c.close()
        return mid

    def _enforce_critical_limit(self, max_critical: int = 15):
        """
        确保活跃 CRITICAL 记忆不超过 max_critical 条。
        超出时软删除最旧的（按 id ASC，先入先出）。
        """
        c = self.conn.cursor()
        c.execute('''
            SELECT COUNT(*) FROM memories 
            WHERE is_active = 1 AND priority = 0
        ''')
        count = c.fetchone()[0]
        if count >= max_critical:
            # 软删除最旧的（id 最小 = 最早写入）
            overflow = count - max_critical + 1  # +1 为即将插入的腾位
            c.execute('''
                UPDATE memories SET is_active = 0, updated_at = CURRENT_TIMESTAMP
                WHERE id IN (
                    SELECT id FROM memories 
                    WHERE is_active = 1 AND priority = 0
                    ORDER BY id ASC LIMIT ?
                )
            ''', (overflow,))
            self.conn.commit()
            logger.info(f"CRITICAL FIFO 淘汰: 软删除 {overflow} 条旧记忆 (阈值={max_critical})")
        c.close()

# NOTE: 2026-05-02 12:05:40, self-evolved by tea_agent --- update_memory 提升到 CRITICAL 时也触发 FIFO 淘汰
    def update_memory(self, memory_id: int, **fields) -> bool:
        """
        更新指定记忆的字段。

        支持的字段: content, category, priority, importance, 
                     expires_at, is_active, tags, last_accessed_at

        Returns:
            是否成功更新（无匹配行时返回 False）
        """
        allowed = {
            "content", "category", "priority", "importance",
            "expires_at", "is_active", "tags", "last_accessed_at"
        }
        updates = {k: v for k, v in fields.items() if k in allowed}
        if not updates:
            return False

        # NOTE: 2026-05-02, self-evolved by tea_agent ---
        # 如果优先级被提升到 CRITICAL，先检查上限
        if updates.get("priority") == 0:
            self._enforce_critical_limit(max_critical=15)

        # 自动更新 updated_at
        updates["updated_at"] = "CURRENT_TIMESTAMP"

        set_clause = ", ".join(
            f"{k} = ?" if k != "updated_at" else f"{k} = CURRENT_TIMESTAMP"
            for k in updates
        )
        values = [v for k, v in updates.items() if k != "updated_at"]

        c = self.conn.cursor()
        c.execute(
            f"UPDATE memories SET {set_clause} WHERE id = ?",
            values + [memory_id]
        )
        self.conn.commit()
        affected = c.rowcount
        c.close()
        return affected > 0

    def deactivate_memory(self, memory_id: int) -> bool:
        """软删除：将记忆标记为失效（is_active=0）"""
        return self.update_memory(memory_id, is_active=0)

    def delete_memory(self, memory_id: int) -> bool:
        """硬删除：从数据库中彻底移除记忆"""
        c = self.conn.cursor()
        c.execute("DELETE FROM memories WHERE id = ?", (memory_id,))
        self.conn.commit()
        affected = c.rowcount
        c.close()
        return affected > 0

    def get_active_memories(self, limit: int = 50) -> List[Dict]:
        """
        获取所有有效记忆（is_active=1 且未过期）。

        Args:
            limit: 返回数量上限

        Returns:
            按优先级排序（CRITICAL 优先，然后最近访问时间倒序）
        """
        self.cleanup_expired_memories()
        c = self.conn.cursor()
        c.execute('''
            SELECT * FROM memories 
            WHERE is_active = 1
            ORDER BY priority ASC, last_accessed_at DESC
            LIMIT ?
        ''', (limit,))
        rows = c.fetchall()
        c.close()
        return [dict(r) for r in rows]

    def get_instructions(self) -> List[Dict]:
        """
        获取所有有效指令级记忆（priority=0, CRITICAL）。

        指令是最高优先级的约束性记忆，例如"代码修改前缀格式"等规则。
        """
        self.cleanup_expired_memories()
        c = self.conn.cursor()
        c.execute('''
            SELECT * FROM memories 
            WHERE is_active = 1 AND priority = 0
            ORDER BY last_accessed_at DESC
        ''')
        rows = c.fetchall()
        c.close()
        return [dict(r) for r in rows]

    def search_memories(
        self,
        query: str = "",
        category: str = "",
        tags: Optional[List[str]] = None,
        min_importance: int = 0,
        limit: int = 20,
    ) -> List[Dict]:
        """
        搜索记忆：关键词模糊匹配 + 分类过滤 + 标签过滤。

        Args:
            query: 在 content 中模糊匹配的关键词
            category: 按分类过滤（空=不过滤）
            tags: 标签列表，匹配任一标签即可
            min_importance: 最低重要度
            limit: 返回数量上限
        """
        self.cleanup_expired_memories()

        conditions = ["is_active = 1"]
        params: list = []

        if query:
            conditions.append("content LIKE ?")
            params.append(f"%{query}%")

        if category:
            conditions.append("category = ?")
            params.append(category)

        if min_importance:
            conditions.append("importance >= ?")
            params.append(min_importance)

        where = " AND ".join(conditions)

        c = self.conn.cursor()
        c.execute(f'''
            SELECT * FROM memories 
            WHERE {where}
            ORDER BY priority ASC, last_accessed_at DESC
            LIMIT ?
        ''', params + [limit])
        rows = c.fetchall()
        c.close()

        results = [dict(r) for r in rows]

        # 标签过滤（Python 侧，简单匹配）
        if tags:
            tag_set = set(t.lower() for t in tags)
            results = [
                r for r in results
                if tag_set & set(t.strip().lower() for t in (r.get("tags", "") or "").split(","))
            ]

        return results[:limit]

    def cleanup_expired_memories(self) -> int:
        """
        清理过期记忆：将 expires_at 已过去的记忆翻为 is_active=0。

        Returns:
            被清理的记忆数量
        """
        c = self.conn.cursor()
        c.execute('''
            UPDATE memories 
            SET is_active = 0, updated_at = CURRENT_TIMESTAMP
            WHERE is_active = 1 
              AND expires_at IS NOT NULL 
              AND expires_at < datetime('now')
        ''')
        self.conn.commit()
        affected = c.rowcount
        c.close()
        return affected

    def touch_memory(self, memory_id: int):
        """更新记忆的最后访问时间（注入时调用）"""
        c = self.conn.cursor()
        c.execute(
            "UPDATE memories SET last_accessed_at = CURRENT_TIMESTAMP WHERE id = ?",
            (memory_id,)
        )
        self.conn.commit()
        c.close()

    def get_memory_stats(self) -> Dict:
        """获取记忆统计信息"""
        c = self.conn.cursor()
        c.execute("SELECT COUNT(*) as total FROM memories WHERE is_active = 1")
        total = c.fetchone()["total"]

        c.execute('''
            SELECT category, COUNT(*) as cnt 
            FROM memories 
            WHERE is_active = 1 
            GROUP BY category
        ''')
        by_category = {r["category"]: r["cnt"] for r in c.fetchall()}

        c.execute('''
            SELECT priority, COUNT(*) as cnt 
            FROM memories 
            WHERE is_active = 1 
            GROUP BY priority
        ''')
        by_priority = {r["priority"]: r["cnt"] for r in c.fetchall()}

        c.close()
        return {
            "total": total,
            "by_category": by_category,
            "by_priority": by_priority,
        }


# NOTE: 2026-04-30 16:14:28, self-evolved by tea_agent --- 新增3张表的CRUD方法：system_prompts(6个)、reflections(4个)、config_history(3个)
    # ============================================================
    # 2026-04-30 gen by deepseek-v4-pro, 系统提示词版本管理 CRUD
    # ============================================================

    def add_system_prompt(self, content: str, reason: str = "", source_reflection_id: Optional[int] = None) -> int:
        """添加新版本系统提示词，自动递增版本号，返回新ID"""
        # 获取当前最大版本号
        c = self.conn.cursor()
        c.execute("SELECT MAX(CAST(version AS INTEGER)) FROM system_prompts")
        row = c.fetchone()
        max_ver = (row[0] or 0) if row else 0
        new_ver = str(max_ver + 1)

        c.execute(
            "INSERT INTO system_prompts (version, content, reason, source_reflection_id) VALUES (?, ?, ?, ?)",
            (new_ver, content, reason, source_reflection_id)
        )
        self.conn.commit()
        pid = cast(int, c.lastrowid)
        c.close()
        return pid

    def get_latest_system_prompt(self) -> Optional[Dict]:
        """获取最新的活跃系统提示词"""
        c = self.conn.cursor()
        c.execute(
            "SELECT * FROM system_prompts WHERE is_active = 1 ORDER BY CAST(version AS INTEGER) DESC LIMIT 1"
        )
        row = c.fetchone()
        c.close()
        return dict(row) if row else None

    def get_system_prompt_history(self, limit: int = 20) -> List[Dict]:
        """获取系统提示词版本历史"""
        c = self.conn.cursor()
        c.execute(
            "SELECT * FROM system_prompts ORDER BY CAST(version AS INTEGER) DESC LIMIT ?",
            (limit,)
        )
        rows = c.fetchall()
        c.close()
        return [dict(r) for r in rows]

    def deactivate_system_prompt(self, prompt_id: int) -> bool:
        """停用某版本系统提示词"""
        c = self.conn.cursor()
        c.execute("UPDATE system_prompts SET is_active = 0 WHERE id = ?", (prompt_id,))
        self.conn.commit()
        affected = c.rowcount
        c.close()
        return affected > 0

    def rollback_system_prompt(self, prompt_id: int) -> bool:
        """回滚：停用当前活跃版本，启用指定版本"""
        c = self.conn.cursor()
        # 停用所有活跃版本
        c.execute("UPDATE system_prompts SET is_active = 0 WHERE is_active = 1")
        # 启用指定版本
        c.execute("UPDATE system_prompts SET is_active = 1 WHERE id = ?", (prompt_id,))
        self.conn.commit()
        affected = c.rowcount
        c.close()
        return affected > 0

    def get_system_prompt_count(self) -> int:
        """获取系统提示词版本计数"""
        c = self.conn.cursor()
        c.execute("SELECT COUNT(*) FROM system_prompts")
        count = c.fetchone()[0]
        c.close()
        return count

    # ============================================================
    # 2026-04-30 gen by deepseek-v4-pro, 反思记录 CRUD
    # ============================================================

    def add_reflection(
        self,
        summary: str,
        details: str = "",
        tool_stats: Optional[Dict] = None,
        suggestions: Optional[List[str]] = None,
        topic_id: Optional[int] = None,
    ) -> int:
        """添加一条反思记录"""
        import json
        c = self.conn.cursor()
        c.execute(
            "INSERT INTO reflections (topic_id, summary, details, tool_stats, suggestions) VALUES (?, ?, ?, ?, ?)",
            (
                topic_id,
                summary,
                details,
                json.dumps(tool_stats or {}, ensure_ascii=False),
                json.dumps(suggestions or [], ensure_ascii=False),
            )
        )
        self.conn.commit()
        rid = cast(int, c.lastrowid)
        c.close()
        return rid

    def get_recent_reflections(self, limit: int = 10) -> List[Dict]:
        """获取最近的反思记录"""
        c = self.conn.cursor()
        c.execute(
            "SELECT * FROM reflections WHERE is_applied = 0 ORDER BY created_at DESC LIMIT ?",
            (limit,)
        )
        rows = c.fetchall()
        c.close()
        return [dict(r) for r in rows]

    def mark_reflection_applied(self, reflection_id: int):
        """将反思标记为已应用"""
        c = self.conn.cursor()
        c.execute("UPDATE reflections SET is_applied = 1 WHERE id = ?", (reflection_id,))
        self.conn.commit()
        c.close()

    def get_reflection_stats(self) -> Dict:
        """获取反思统计"""
        c = self.conn.cursor()
        c.execute("SELECT COUNT(*) as total FROM reflections")
        total = c.fetchone()["total"]
        c.execute("SELECT COUNT(*) as unapplied FROM reflections WHERE is_applied = 0")
        unapplied = c.fetchone()["unapplied"]
        c.close()
        return {"total": total, "unapplied": unapplied}

    # ============================================================
    # 2026-04-30 gen by deepseek-v4-pro, 配置变更历史 CRUD
    # ============================================================

    def add_config_change(
        self,
        key: str,
        new_value: str,
        old_value: Optional[str] = None,
        reason: str = "",
        source_reflection_id: Optional[int] = None,
    ) -> int:
        """记录一次配置变更"""
        c = self.conn.cursor()
        c.execute(
            "INSERT INTO config_history (key, old_value, new_value, reason, source_reflection_id) VALUES (?, ?, ?, ?, ?)",
            (key, str(old_value) if old_value is not None else None, str(new_value), reason, source_reflection_id)
        )
        self.conn.commit()
        cid = cast(int, c.lastrowid)
        c.close()
        return cid

    def get_config_history(self, key: str = "", limit: int = 20) -> List[Dict]:
        """获取配置变更历史，可按 key 过滤"""
        c = self.conn.cursor()
        if key:
            c.execute(
                "SELECT * FROM config_history WHERE key = ? ORDER BY created_at DESC LIMIT ?",
                (key, limit)
            )
        else:
            c.execute(
                "SELECT * FROM config_history ORDER BY created_at DESC LIMIT ?",
                (limit,)
            )
        rows = c.fetchall()
        c.close()
        return [dict(r) for r in rows]

    def get_config_changes_since(self, since_id: int = 0) -> List[Dict]:
        """获取指定ID之后的配置变更"""
        c = self.conn.cursor()
        c.execute(
            "SELECT * FROM config_history WHERE id > ? ORDER BY created_at ASC",
            (since_id,)
        )
        rows = c.fetchall()
        c.close()
        return [dict(r) for r in rows]

# NOTE: 2026-05-06 19:17:38, self-evolved by tea_agent --- Storage 类新增向量CRUD方法：store_embedding、get_msg_embedding、get_all_embeddings、search_by_vector
    # ============================================================
    # 2026-05-06 gen by claude, 文本向量存储与语义搜索
    # ============================================================

# NOTE: 2026-05-07 07:35:50, self-evolved by tea_agent --- store_embedding 改用 numpy float32 tobytes() 存储
    def store_embedding(self, conversation_id: int, embedding: list, model_name: str = "", dimension: int = 0):
        """为指定 conversation 存储其 user_msg 的文本向量（numpy float32 → BLOB）"""
        import numpy as np
        arr = np.array(embedding, dtype=np.float32)
        blob = arr.tobytes()
        dim = dimension or len(embedding)
        c = self.conn.cursor()
        c.execute('''
            INSERT OR REPLACE INTO msg_vectors (conversation_id, embedding, dimension, model_name, created_at)
            VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP)
        ''', (conversation_id, blob, dim, model_name))
        self.conn.commit()
        c.close()

# NOTE: 2026-05-07 07:36:00, self-evolved by tea_agent --- get_msg_embedding 改用 np.frombuffer 反序列化 BLOB
    def get_msg_embedding(self, conversation_id: int) -> Optional[List[float]]:
        """获取指定 conversation 的文本向量（BLOB → float list）"""
        import numpy as np
        c = self.conn.cursor()
        c.execute('SELECT embedding, dimension FROM msg_vectors WHERE conversation_id = ?', (conversation_id,))
        row = c.fetchone()
        c.close()
        if row and row["embedding"]:
            try:
                arr = np.frombuffer(row["embedding"], dtype=np.float32)
                return arr.tolist()
            except Exception:
                return None
        return None

# NOTE: 2026-05-07 07:36:44, self-evolved by tea_agent --- get_all_embeddings 改用 np.frombuffer 反序列化 BLOB
    def get_all_embeddings(self) -> List[Dict]:
        """
        获取所有已存储的向量及其关联信息。
        
        Returns:
            [{"conversation_id": int, "embedding": [float,...], "user_msg": str,
              "topic_id": int, "topic_title": str}, ...]
        """
        import numpy as np
        c = self.conn.cursor()
        c.execute('''
            SELECT v.conversation_id, v.embedding, c.user_msg, c.topic_id, t.title as topic_title
            FROM msg_vectors v
            JOIN conversations c ON v.conversation_id = c.id
            JOIN topics t ON c.topic_id = t.topic_id
            ORDER BY v.created_at DESC
        ''')
        rows = c.fetchall()
        c.close()
        results = []
        for row in rows:
            d = dict(row)
            blob = d.pop("embedding", None)
            if blob:
                try:
                    d["embedding"] = np.frombuffer(blob, dtype=np.float32).tolist()
                except Exception:
                    d["embedding"] = None
            else:
                d["embedding"] = None
            results.append(d)
        return results

# NOTE: 2026-05-07 07:38:57, self-evolved by tea_agent --- search_by_vector 改用 numpy 向量化余弦相似度 + 批量 ai_msg 查询
    def search_by_vector(self, query_embedding: List[float], top_k: int = 10,
                          min_similarity: float = 0.3) -> List[Dict]:
        """
        根据查询向量进行余弦相似度搜索（numpy 向量化），返回最匹配的消息。

        Args:
            query_embedding: 查询文本的向量
            top_k: 返回结果数
            min_similarity: 最低相似度阈值

        Returns:
            [{"conversation_id": int, "similarity": float, "user_msg": str,
              "ai_msg": str, "topic_id": int, "topic_title": str}, ...]
        """
        import numpy as np

        all_embs = self.get_all_embeddings()
        if not all_embs:
            return []

        query_arr = np.array(query_embedding, dtype=np.float32)
        q_norm = np.linalg.norm(query_arr)
        if q_norm == 0:
            return []

        # 批量构建矩阵
        valid_items = []
        vecs = []
        for item in all_embs:
            emb = item.get("embedding")
            if not emb or len(emb) != len(query_embedding):
                continue
            vecs.append(emb)
            valid_items.append(item)
        if not vecs:
            return []

        # 向量化余弦相似度: (Q·M^T) / (|Q| * |M_i|)
        mat = np.array(vecs, dtype=np.float32)
        dots = mat @ query_arr
        mat_norms = np.linalg.norm(mat, axis=1)
        sims = dots / (q_norm * mat_norms)

        scored = []
        for i, sim in enumerate(sims):
            if sim >= min_similarity:
                scored.append({
                    "conversation_id": valid_items[i]["conversation_id"],
                    "similarity": round(float(sim), 4),
                    "user_msg": valid_items[i]["user_msg"],
                    "topic_id": valid_items[i]["topic_id"],
                    "topic_title": valid_items[i]["topic_title"],
                })

        scored.sort(key=lambda x: x["similarity"], reverse=True)
        top = scored[:top_k]
        if not top:
            return []

        # 批量补充 ai_msg（一条查询代替 N 条）
        c = self.conn.cursor()
        cids = tuple(s["conversation_id"] for s in top)
        placeholders = ",".join("?" for _ in cids)
        c.execute(
            f"SELECT id, ai_msg FROM conversations WHERE id IN ({placeholders})",
            cids,
        )
        ai_map = {row["id"]: row["ai_msg"] or "" for row in c.fetchall()}
        c.close()
        for s in top:
            s["ai_msg"] = ai_map.get(s["conversation_id"], "")

        return top

# NOTE: 2026-05-06 19:21:23, self-evolved by tea_agent --- 新增 search_by_keyword 方法作为向量搜索的关键词回退
    def search_by_keyword(self, query: str, top_k: int = 50) -> List[Dict]:
        """
        关键词模糊搜索（LIKE 匹配），用于向量不可用时的回退。

        Args:
            query: 搜索关键词
            top_k: 返回结果数

        Returns:
            [{"conversation_id": int, "similarity": float, "user_msg": str,
              "ai_msg": str, "topic_id": int, "topic_title": str}, ...]
        """
        c = self.conn.cursor()
        # 在所有 user_msg 中模糊搜索
        c.execute('''
            SELECT c.id as conversation_id, c.user_msg, c.ai_msg, c.topic_id, t.title as topic_title
            FROM conversations c
            JOIN topics t ON c.topic_id = t.topic_id
            WHERE c.user_msg LIKE ?
            ORDER BY c.stamp DESC
            LIMIT ?
        ''', (f"%{query}%", top_k))
        rows = c.fetchall()
        c.close()
        # 简单的相似度分数：查询词在消息中的出现频率
        results = []
        qlen = len(query) if query else 1
        for row in rows:
            d = dict(row)
            user_msg = d.get("user_msg", "") or ""
            # 简单的包含度分数
            score = user_msg.lower().count(query.lower()) * len(query) / max(len(user_msg), 1)
            d["similarity"] = min(round(score * 10, 4), 1.0)  # scale to 0~1
            results.append(d)
        results.sort(key=lambda x: x["similarity"], reverse=True)
        return results

    def get_vector_count(self) -> int:
        """已存储向量的消息数量"""
        c = self.conn.cursor()
        c.execute("SELECT COUNT(*) FROM msg_vectors")
        count = c.fetchone()[0]
        c.close()
        return count

    def get_unvectorized_conversations(self, limit: int = 100) -> List[Dict]:
        """
        获取尚未生成向量的 conversation（仅限有 user_msg 的）。
        用于批量生成向量。
        """
        c = self.conn.cursor()
        c.execute('''
            SELECT c.id, c.user_msg, c.topic_id
            FROM conversations c
            LEFT JOIN msg_vectors v ON c.id = v.conversation_id
            WHERE v.conversation_id IS NULL AND c.user_msg != ''
            ORDER BY c.stamp DESC
            LIMIT ?
        ''', (limit,))
        rows = c.fetchall()
        c.close()
        return [dict(r) for r in rows]

# NOTE: 2026-05-06 19:22:03, self-evolved by tea_agent --- Storage 新增 vectorize_conversation 和 batch_vectorize 方法
    def vectorize_conversation(self, conversation_id: int, user_msg: str,
                                 model_name: str = "", embedding: Optional[List[float]] = None) -> bool:
        """
        为单个 conversation 生成并存储向量。若提供 embedding 则直接存储，
        否则需要外部调用 embedding_util 生成后传入。

        Returns:
            是否成功存储
        """
        if not embedding:
            return False
        self.store_embedding(conversation_id, embedding, model_name, len(embedding))
        return True

    def batch_vectorize(self, conversation_data: List[Dict], model_name: str = "") -> int:
        """
        批量存储向量。conversation_data 每项需含:
        {"conversation_id": int, "embedding": [float,...]}

        Returns:
            成功存储的数量
        """
        count = 0
        for item in conversation_data:
            cid = item.get("conversation_id")
            emb = item.get("embedding")
            if cid and emb:
                self.store_embedding(cid, emb, model_name, len(emb))
                count += 1
        return count

    def delete_vector(self, conversation_id: int):
        """删除指定 conversation 的向量"""
        c = self.conn.cursor()
        c.execute('DELETE FROM msg_vectors WHERE conversation_id = ?', (conversation_id,))
        self.conn.commit()
        c.close()

# NOTE: 2026-05-04 17:15:28, self-evolved by tea_agent --- 新增 Storage.close() 方法：wal_checkpoint(TRUNCATE) 合并 WAL + 关闭连接
    # ============================================================
    # 2026-05-05 gen by deepseek-v4-pro, 正常关闭：checkpoint WAL + close
    # ============================================================

    def close(self):
        """
        正常关闭数据库连接。
        执行 WAL checkpoint (TRUNCATE) 将 WAL 文件合并回主 DB，
        然后删除 .db-wal 和 .db-shm 文件，最后关闭连接。
        """
        try:
            # TRUNCATE 模式：checkpoint 后删除 WAL 文件（而非 PASSIVE 仅截断）
            self.conn.execute("PRAGMA wal_checkpoint(TRUNCATE)")
            logger.info("WAL checkpoint(TRUNCATE) 完成")
        except Exception as e:
            logger.warning(f"WAL checkpoint 失败 (非致命): {e}")
        finally:
            try:
                self.conn.close()
                logger.info(f"数据库连接已关闭: {self.db_path}")
            except Exception:
                pass

    # ── 自动备份 ──
    # NOTE: 2026-05-08 gen by tea_agent, 定时备份数据库防止损坏
    def _auto_backup(self):
        """启动时检查并备份数据库（距离上次备份 > 1 小时才执行）"""
        import time
        try:
            now = time.time()
            last = self._meta_get("last_backup_ts")
            if last:
                try:
                    if now - float(last) < 3600:  # 1 小时内备份过，跳过
                        return
                except ValueError:
                    pass

            backup_dir = os.path.join(os.path.dirname(os.path.abspath(self.db_path)), "backup")
            os.makedirs(backup_dir, exist_ok=True)
            ts = time.strftime("%Y-%m-%d_%H%M%S")
            backup_path = os.path.join(backup_dir, f"chat_history_{ts}.db")

            # 使用 sqlite3 内置 backup API，在线热备不阻塞
            backup_conn = sqlite3.connect(backup_path)
            self.conn.backup(backup_conn)
            backup_conn.close()

            self._meta_set("last_backup_ts", str(now))
            self._cleanup_backups(backup_dir, keep=7)

            size_mb = os.path.getsize(backup_path) / 1024 / 1024
            logger.info(f"数据库已备份: {backup_path} ({size_mb:.1f}MB)")
        except Exception as e:
            logger.debug(f"自动备份跳过: {e}")

    def _cleanup_backups(self, backup_dir: str, keep: int = 7):
        """清理旧备份，只保留最近 keep 个"""
        try:
            files = sorted(
                [f for f in os.listdir(backup_dir) if f.startswith("chat_history_") and f.endswith(".db")],
                reverse=True
            )
            for old in files[keep:]:
                p = os.path.join(backup_dir, old)
                os.remove(p)
                logger.debug(f"清理旧备份: {p}")
        except Exception:
            pass

    # ── 元数据读写 ──
    def _meta_get(self, key: str) -> Optional[str]:
        try:
            c = self.conn.execute("SELECT value FROM _meta WHERE key=?", (key,))
            row = c.fetchone()
            return row[0] if row else None
        except Exception:
            return None

    def _meta_set(self, key: str, value: str):
        try:
            self.conn.execute(
                "INSERT OR REPLACE INTO _meta (key, value) VALUES (?, ?)",
                (key, value)
            )
            self.conn.commit()
        except Exception:
            pass

# NOTE: 2026-05-09 19:59:45, self-evolved by tea_agent --- 添加 _protect_db() 方法：在数据库目录创建保护标记文件
    def _protect_db(self):
        """在数据库同目录创建 .chat_history_protected 标记文件，防止 Agent 误删。

        标记文件不影响数据库正常运行，仅作为保护提醒。
        toolkit_file 写入操作会检查此标记并拒绝覆盖受保护文件。
        """
        import os as _os
        db_abs = _os.path.abspath(self.db_path)
        db_dir = _os.path.dirname(db_abs)
        marker = _os.path.join(db_dir, ".chat_history_protected")
        try:
            if not _os.path.exists(marker):
                with open(marker, "w") as f:
                    f.write(f"# 此标记文件保护数据库不被意外删除\n")
                    f.write(f"# 数据库路径: {db_abs}\n")
                    f.write(f"# 创建时间: {__import__('datetime').datetime.now().isoformat()}\n")
        except Exception:
            pass  # 标记文件创建失败不影响数据库正常运行

    def backup_now(self):
        """手动触发备份（跳过时间检查）"""
        self._meta_set("last_backup_ts", "0")
        self._auto_backup()

    # ── 析构 ──

    def __del__(self):
        """析构函数：安全兜底关闭连接（不抛异常）"""
        try:
            self.close()
        except Exception:
            pass


# ---- 模块级便捷方法，供 toolkit 工具使用 ----

_storage_instance = None


# NOTE: 2026-05-04 17:54:39, self-evolved by tea_agent --- get_storage() 默认从 config.paths 读取 db_path，支持多 agent
# @2026-04-29 gen by deepseek-v4-pro, 模块级get_storage单例供工具使用
def get_storage(db_path: str = "") -> "Storage":
    """获取或创建 Storage 单例（供工具函数使用）。
    
    优先从 config.paths.db_path_abs 读取路径，否则回退到 chat_history.db。
    """
    global _storage_instance
    if not db_path:
        try:
            from tea_agent.config import get_config
            db_path = get_config().paths.db_path_abs
        except Exception:
            db_path = "chat_history.db"
    if _storage_instance is None or _storage_instance.db_path != db_path:
        _storage_instance = Storage(db_path)
    return _storage_instance
