## llm generated tool func, created Fri Apr 17 21:02:03 2026

def toolkit_code_comment(description: str) -> str:
    """生成代码修改注释前缀
    格式: '@{date} generated by {model_name}, {description}'
    
    Args:
        description: 修改的简单描述
        
    Returns:
        str: 注释前缀字符串
    """
    from datetime import datetime
    import os
    
    now = datetime.now()
    date_str = now.strftime("%Y-%m-%d %H:%M:%S")
    model_name = os.environ.get("TEA_AGENT_MODEL", "unknown_model")
    return f"@{date_str} generated by {model_name}, {description}"

def meta_toolkit_code_comment() -> dict:
    return {"type": "function", "function": {"name": "toolkit_code_comment", "description": "生成代码修改注释前缀，格式为 '@{date} generated by {model_name}, {description}'。使用本地 datetime 确保独立运行。", "parameters": {"properties": {"description": {"description": "修改的简单描述", "type": "string"}}, "required": ["description"], "type": "object"}}}
