# @2026-04-29 gen by deepseek-v4-pro
# version: 1.1.0 — 移除 evolve 模式

import logging

logger = logging.getLogger("toolkit")

def toolkit_comment(mode: str, description: str = "", model_name: str = ""):
    """
    生成代码修改注释前缀。

    mode="code": 代码修改注释，格式 '@{datetime} generated by {model}, {description}'
      需 description，model_name 可选（默认取环境变量 TEA_AGENT_MODEL）
    """
    logger.info(f"toolkit_comment called: mode={mode!r}, description={repr(description)[:80]}, model_name={model_name!r}")

    from datetime import datetime
    import os

    now = datetime.now()

    if mode == "code":
        date_str = now.strftime("%Y-%m-%d %H:%M:%S")
        mdl = model_name if model_name else os.environ.get("TEA_AGENT_MODEL", "unknown_model")
        return f"@{date_str} generated by {mdl}, {description}"

    else:
        return f"未知 mode: '{mode}'，可选: code"


def meta_toolkit_comment() -> dict:
    """Meta toolkit comment."""
    return {
        "type": "function",
        "function": {
            "name": "toolkit_comment",
            "description": "生成代码修改注释前缀。mode='code' 生成修改注释(@{date} gen by {model}, {desc})。",
            "parameters": {
                "type": "object",
                "properties": {
                    "mode": {
                        "type": "string",
                        "enum": ["code"],
                        "description": "注释模式：code=代码修改注释",
                    },
                    "description": {
                        "type": "string",
                        "description": "[mode=code] 修改的简单描述",
                    },
                    "model_name": {
                        "type": "string",
                        "description": "[mode=code] 模型名称，不传则自动获取",
                    },
                },
                "required": ["mode"],
            },
        },
    }
