# @2026-04-29 gen by deepseek-v4-pro, 合并2个comment工具（code_comment + evolve_comment）
# version: 1.0.0

def toolkit_comment(mode: str, description: str = "", model_name: str = ""):
    """
    生成代码注释前缀，两种模式：
    - mode="code": 代码修改注释，格式 '@{datetime} generated by {model}, {description}'
      需 description，model_name 可选（默认取环境变量 TEA_AGENT_MODEL）
    - mode="evolve": 自进化注释，格式 '# NOTE: {date}, self-evolved by {model} ---'
      需 model_name
    """
    from datetime import datetime
    import os

    now = datetime.now()

    if mode == "code":
        date_str = now.strftime("%Y-%m-%d %H:%M:%S")
        mdl = model_name if model_name else os.environ.get("TEA_AGENT_MODEL", "unknown_model")
        return f"@{date_str} generated by {mdl}, {description}"

    elif mode == "evolve":
        date_str = now.strftime("%Y-%m-%d")
        mdl = model_name or "tea_agent"
        return f"# NOTE: {date_str}, self-evolved by {mdl} ---"

    else:
        return f"❌ 未知 mode: '{mode}'，可选: code / evolve"


def meta_toolkit_comment() -> dict:
    return {
        "type": "function",
        "function": {
            "name": "toolkit_comment",
            "description": "生成代码注释前缀。mode='code' 生成修改注释(@{date} gen by {model}, {desc})；mode='evolve' 生成自进化注释(# NOTE: {date}, self-evolved by {model} ---)。",
            "parameters": {
                "type": "object",
                "properties": {
                    "mode": {
                        "type": "string",
                        "enum": ["code", "evolve"],
                        "description": "注释模式：code=代码修改注释, evolve=自进化注释",
                    },
                    "description": {
                        "type": "string",
                        "description": "[mode=code] 修改的简单描述",
                    },
                    "model_name": {
                        "type": "string",
                        "description": "[mode=code/evolve] 模型名称，不传则自动获取",
                    },
                },
                "required": ["mode"],
            },
        },
    }
