"""
DagDotRenderer — 将 WorkflowDAG 执行状态渲染为 DOT (Graphviz) 格式。

功能:
  - dag_to_dot(dag, node_states) → DOT 字符串
  - render_dot_to_svg(dot_str) → SVG 字符串 (需要 dot 命令)
  - render_dot_to_png(dot_str) → PNG bytes (需要 dot 命令)
  - check_dot_available() → bool

用法:
    from tea_agent.multi_agent.dag_dot_renderer import dag_to_dot, render_dot_to_svg

    dot = dag_to_dot(viz.dag, viz._exec.results)
    svg = render_dot_to_svg(dot)  # 或 None 如果 dot 不可用
"""

from __future__ import annotations

import logging
import os
import subprocess
from typing import Any

logger = logging.getLogger(__name__)


# ═══════════════════════════════════════════════
# 状态 → 颜色映射（Graphviz 兼容）
# ═══════════════════════════════════════════════

_STATE_COLORS = {
    "pending":     ("#21262d", "#30363d", "#8b949e"),
    "ready":       ("#1f6feb22", "#1f6feb", "#58a6ff"),
    "running":     ("#1f6feb44", "#58a6ff", "#ffffff"),
    "completed":   ("#23863622", "#3fb950", "#3fb950"),
    "failed":      ("#da363322", "#f85149", "#f85149"),
    "skipped":     ("#161b22", "#484f58", "#484f58"),
    "cancelled":   ("#161b22", "#8b949e", "#8b949e"),
}

_DOT_BIN: str | None = None  # 缓存路径


def _find_dot() -> str | None:
    """查找 Graphviz dot 可执行文件路径。"""
    global _DOT_BIN
    if _DOT_BIN is not None:
        return _DOT_BIN

    # 常见路径 (Windows + Linux)
    candidates = [
        r"C:\Program Files\Graphviz\bin\dot.exe",
        r"C:\Program Files (x86)\Graphviz\bin\dot.exe",
    ]
    for path in candidates:
        if os.path.isfile(path):
            _DOT_BIN = path
            return path

    # 尝试 PATH 查找
    try:
        result = subprocess.run(
            ["dot", "-V"],
            capture_output=True,
            timeout=5,
            text=True,
        )
        if result.returncode == 0:
            _DOT_BIN = "dot"
            return "dot"
    except (FileNotFoundError, subprocess.TimeoutExpired):
        pass

    return None


def check_dot_available() -> bool:
    """检查 Graphviz dot 是否可用。"""
    return _find_dot() is not None


# ═══════════════════════════════════════════════
# DOT 生成
# ═══════════════════════════════════════════════

def dag_to_dot(
    dag: Any,  # WorkflowDAG
    node_states: dict[str, Any],  # {node_id: NodeResult}
    title: str = "Workflow DAG",
    orientation: str = "LR",  # LR=水平, TB=垂直
) -> str:
    """
    将 DAG 结构 + 节点状态转换为 DOT 語言格式。

    Args:
        dag: WorkflowDAG 实例
        node_states: {node_id: NodeResult} 字典
        title: 图表标题
        orientation: 布局方向 (LR=水平, TB=垂直)

    Returns:
        DOT 格式字符串
    """
    lines = []
    lines.append(f"// {title} — generated by DagDotRenderer")
    lines.append("digraph G {")
    lines.append(f'  rankdir={orientation};')
    lines.append(f'  label="{title}";')
    lines.append('  labelloc=t;')
    lines.append('  fontsize=18;')
    lines.append('  fontname="sans-serif";')
    lines.append('  fontcolor="#c9d1d9";')
    lines.append('  bgcolor="#0d1117";')
    lines.append('  node [fontname="sans-serif" fontsize=11 shape=box style=rounded];')
    lines.append('  edge [color="#30363d" fontcolor="#8b949e" fontsize=9];')
    lines.append("")

    # 节点
    for nid, node in dag.nodes.items():
        state_info = node_states.get(nid)
        state = state_info.state.value if state_info else "pending"
        fill, stroke, fontcolor = _STATE_COLORS.get(state, _STATE_COLORS["pending"])

        label_parts = []
        label_parts.append(node.label or nid)

        duration_str = ""
        if state_info:
            label_parts.append(f"[{state.upper()}]")
            if state_info.duration > 0:
                duration_str = f" ({state_info.duration:.1f}s)"
                label_parts[-1] = f"[{state.upper()}{duration_str}]"
            if state_info.error:
                escaped_err = state_info.error.replace('"', '\\"')[:60]
                label_parts.append(f"⚠ {escaped_err}")

        label = "\\n".join(label_parts)

        lines.append(
            f'  "{nid}" ['
            f'label="{label}", '
            f'fillcolor="{fill}", '
            f'color="{stroke}", '
            f'fontcolor="{fontcolor}", '
            f'penwidth=2'
            f'];'
        )

    lines.append("")

    # 边
    for edge in dag.edges:
        from_id = edge["from"]
        to_id = edge["to"]
        cond = edge.get("condition_key")
        if cond:
            lines.append(f'  "{from_id}" -> "{to_id}" [label="{cond}" fontsize=9];')
        else:
            lines.append(f'  "{from_id}" -> "{to_id}";')

    lines.append("}")
    return "\n".join(lines)


# ═══════════════════════════════════════════════
# DOT → 图像渲染
# ═══════════════════════════════════════════════

def render_dot_to_svg(dot_str: str) -> str | None:
    """
    使用 Graphviz dot 将 DOT 字符串渲染为 SVG。

    Args:
        dot_str: DOT 格式字符串

    Returns:
        SVG 字符串，或 None 如果 dot 不可用/失败
    """
    dot_bin = _find_dot()
    if not dot_bin:
        return None

    try:
        result = subprocess.run(
            [dot_bin, "-Tsvg"],
            input=dot_str,
            capture_output=True,
            timeout=15,
            text=True,
        )
        if result.returncode == 0 and result.stdout.strip():
            return result.stdout
        logger.warning(f"dot SVG 渲染失败: {result.stderr[:200]}")
        return None
    except (subprocess.TimeoutExpired, OSError) as e:
        logger.warning(f"dot 调用异常: {e}")
        return None


def render_dot_to_png(dot_str: str) -> bytes | None:
    """
    使用 Graphviz dot 将 DOT 字符串渲染为 PNG。

    Args:
        dot_str: DOT 格式字符串

    Returns:
        PNG bytes，或 None 如果 dot 不可用/失败
    """
    dot_bin = _find_dot()
    if not dot_bin:
        return None

    try:
        result = subprocess.run(
            [dot_bin, "-Tpng"],
            input=dot_str.encode("utf-8"),
            capture_output=True,
            timeout=15,
        )
        if result.returncode == 0 and len(result.stdout) > 100:
            return result.stdout
        logger.warning(f"dot PNG 渲染失败: {result.stderr[:200]}")
        return None
    except (subprocess.TimeoutExpired, OSError) as e:
        logger.warning(f"dot 调用异常: {e}")
        return None


# ═══════════════════════════════════════════════
# 高级封装：直接从 WorkflowVisualizer 生成
# ═══════════════════════════════════════════════

def render_viz_snapshot(viz: Any) -> dict:
    """
    从 WorkflowVisualizer 实例生成完整快照（DOT + SVG + PNG）。

    Args:
        viz: WorkflowVisualizer 实例

    Returns:
        {
            "dot": str,           # DOT 源码
            "svg": str | None,    # SVG 渲染
            "png": bytes | None,  # PNG 渲染
            "dot_available": bool,
        }
    """
    node_states = viz._exec.results if viz._exec else {}

    dot = dag_to_dot(viz.dag, node_states, viz.title)
    dot_avail = check_dot_available()

    result = {
        "dot": dot,
        "svg": None,
        "png": None,
        "dot_available": dot_avail,
    }

    if dot_avail:
        result["svg"] = render_dot_to_svg(dot)
        result["png"] = render_dot_to_png(dot)

    return result


def render_dag_dict_to_svg(dag_data: dict) -> str | None:
    """
    从简单的 {nodes, edges, title} 字典渲染 SVG。

    与 server 路由和 SimpleDagRegistry 配合使用，不依赖 WorkflowVisualizer。

    Args:
        dag_data: {
            "title": str,
            "nodes": [{"id": str, "label": str, "state": str, "duration": float, "error": str}],
            "edges": [{"from": str, "to": str}],
        }

    Returns:
        SVG 字符串，或 None
    """
    if not check_dot_available():
        return None

    # 构建临时 WorkflowDAG
    from .workflow_engine import NodeType, WorkflowDAG, WorkflowNode

    dag = WorkflowDAG()
    for n in dag_data.get("nodes", []):
        node = WorkflowNode(
            node_id=n["id"],
            type=NodeType(n.get("type", "task")),
            label=n.get("label", n["id"]),
        )
        dag.add_node(node)
    for e in dag_data.get("edges", []):
        dag.add_edge(e["from"], e["to"], condition_key=e.get("condition_key"))

    # 构建 node_states 伪对象
    from dataclasses import dataclass
    @dataclass
    class _NR:
        state: _NS
        duration: float = 0
        error: str | None = None
    @dataclass
    class _NS:
        value: str = "pending"

    node_states = {}
    for n in dag_data.get("nodes", []):
        s = n.get("state", "pending")
        node_states[n["id"]] = _NR(
            state=_NS(value=s),
            duration=n.get("duration", 0),
            error=n.get("error"),
        )

    title = dag_data.get("title", "Workflow DAG")
    dot = dag_to_dot(dag, node_states, title)
    return render_dot_to_svg(dot)


def render_dag_dict_to_png(dag_data: dict) -> bytes | None:
    """
    从简单的 {nodes, edges, title} 字典渲染 PNG。

    Args:
        dag_data: 同 render_dag_dict_to_svg

    Returns:
        PNG 字节，或 None
    """
    if not check_dot_available():
        return None

    from dataclasses import dataclass

    from .workflow_engine import NodeType, WorkflowDAG, WorkflowNode

    dag = WorkflowDAG()
    for n in dag_data.get("nodes", []):
        node = WorkflowNode(
            node_id=n["id"],
            type=NodeType(n.get("type", "task")),
            label=n.get("label", n["id"]),
        )
        dag.add_node(node)
    for e in dag_data.get("edges", []):
        dag.add_edge(e["from"], e["to"], condition_key=e.get("condition_key"))

    @dataclass
    class _NR:
        state: _NS
        duration: float = 0
        error: str | None = None
    @dataclass
    class _NS:
        value: str = "pending"

    node_states = {}
    for n in dag_data.get("nodes", []):
        s = n.get("state", "pending")
        node_states[n["id"]] = _NR(
            state=_NS(value=s),
            duration=n.get("duration", 0),
            error=n.get("error"),
        )

    title = dag_data.get("title", "Workflow DAG")
    dot = dag_to_dot(dag, node_states, title)
    return render_dot_to_png(dot)

